import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, ELEVATED_WORK_MODIFIERS, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const exteriorPainting = {
  identity: { id: 'exterior-painting', slug: 'exterior-painting', version: '1.0.0', name: 'Exterior Painting', shortName: 'Exterior Painting', description: 'Prepare and paint a small exterior section or similar accessible exterior surface.', category: 'Painting', trade: 'painting', tags: ['painting', 'exterior', 'weather-sensitive'] },
  availability: { residential: true, commercial: true, emergencyEligible: false, afterHoursEligible: false, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 8, typical: 18, maximum: 40 }, quantityUnit: 'squareFoot', setupHours: 1.5, cleanupHours: 1, productionRate: { quantity: 450, unit: 'squareFoot', laborHours: 6, unitsPerTechnicianHour: { minimum: 40, typical: 75, maximum: 110 } }, returnVisits: { minimum: 2, typical: 3, maximum: 5 } },
  materials: { costRange: { minimum: 175, typical: 500, maximum: 1400 }, costUnit: 'typicalProject', typicalMaterials: ['Exterior paint', 'Exterior primer', 'Exterior caulk', 'Patch or filler materials', 'Masking and protection', 'Surface-cleaning supplies', 'Scraping and sanding consumables'], wasteFactorPercentage: 15, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: { typicalEquipment: ['Exterior painting tools', 'Ladders', 'Surface protection'], rentalMayBeRequired: true, rentalCostRange: { minimum: 0, typical: 250, maximum: 1200 }, elevatedAccessPossible: true, specialtyEquipmentNotes: ['Lift or scaffold costs apply only when project-specific access requires them.'] },
  timeline: { onsiteLaborHours: { minimum: 8, typical: 18, maximum: 40 }, calendarDurationDays: { minimum: 2, typical: 4, maximum: 7 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, dryingOrCuringTimeHours: { minimum: 4, typical: 12, maximum: 24 }, returnVisitRequired: true, weatherSensitive: true, permitMayAffectTimeline: false },
  pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 15 },
  estimatorQuestions: [question('surfaceArea', 'Surface area', 'measurement', ['labor', 'materials', 'confidence'], true), question('storyCount', 'Number of stories', 'number', ['labor', 'equipment', 'manualReview'], true), question('substrate', 'Substrate', 'text', ['materials', 'scope'], true), question('currentCondition', 'Current condition', 'singleSelect', ['labor', 'materials']), question('failedCoating', 'Peeling or failed coating', 'boolean', ['labor', 'scope']), question('leadPaintPossible', 'Lead-paint possibility', 'boolean', ['manualReview']), question('accessDifficulty', 'Access', 'singleSelect', ['labor', 'timeline', 'equipment']), question('majorColorChange', 'Color change', 'boolean', ['labor', 'materials']), question('trimIncluded', 'Trim included', 'boolean', ['labor', 'scope']), question('pressureWashingRequired', 'Pressure washing required', 'boolean', ['labor', 'timeline']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, ...ELEVATED_WORK_MODIFIERS, { id: 'exterior-failed-coating', name: 'Failed coating preparation', description: 'Peeling or failed coating needs additional preparation.', conditions: [{ field: 'failedCoating', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2, materialMultiplier: 1.05, scopeStepsToAdd: ['Scrape and prepare accessible failed coating areas.'] }, customerExplanation: 'Failed coatings require additional surface preparation.', internalNotes: [] }, { id: 'exterior-color-change', name: 'Major color change', description: 'Color-change coverage adjustment.', conditions: [{ field: 'majorColorChange', operator: 'equals', value: true }], effects: { laborMultiplier: 1.15, materialMultiplier: 1.15 }, customerExplanation: 'A major color change may require added coating coverage.', internalNotes: [] }, { id: 'exterior-two-story', name: 'Structure above two stories', description: 'High exterior access requires review.', conditions: [{ field: 'storyCount', operator: 'greaterThan', value: 2 }], effects: { requiresManualReview: true, recommendationsToAdd: ['Confirm scaffold or lift requirements.'] }, customerExplanation: 'Structures above two stories require direct access review.', internalNotes: [] }, { id: 'exterior-lead', name: 'Lead-paint possibility', description: 'Potential lead paint requires review.', conditions: [{ field: 'leadPaintPossible', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Potential lead-based paint requires appropriate evaluation.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Measured surface area', 'Substrate', 'Story count', 'Photos'], reducesConfidence: ['Unknown coating condition', 'Unknown access', 'Missing photos'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Inspect visible exterior surfaces.', 'Protect adjacent surfaces and landscaping.', 'Clean and prepare accessible surfaces.', 'Scrape and sand included failed coating.', 'Caulk and prime included areas.', 'Apply included exterior finish coats.'], conditionalSteps: ['Evaluate visible rot, stucco failure, and water intrusion.', 'Coordinate project-specific elevated access.'], cleanupSteps: ['Remove masking and protection.', 'Clean the work area and remove painting debris.'] },
  recommendations: { relatedServices: ['Exterior repairs', 'Window and trim repair'], customerPreparation: ['Confirm exterior colors and included surfaces.', 'Provide clear access around the work area.'], professionalReviewTriggers: ['Structures above two stories', 'Lead-based paint possibility', 'Extensive rot', 'Stucco failure', 'Lift or scaffold requirement', 'Commercial public-access control', 'Active water intrusion'] },
  assumptions: ['Base project represents a small exterior section or approximately 300–600 square feet.', 'Completion remains weather dependent.'],
  exclusions: ['Lead abatement', 'Structural repair', 'Extensive rot reconstruction', 'Weather-delay guarantees'],
  permitsAndCode: { permitMayBeRequired: false, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: false, notes: ['Lead paint and public-access conditions require appropriate review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
