import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, ELEVATED_WORK_MODIFIERS, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const interiorPainting = {
  identity: { id: 'interior-painting', slug: 'interior-painting', version: '1.0.0', name: 'Interior Painting', shortName: 'Interior Painting', description: 'Prepare and paint interior walls and included finish surfaces.', category: 'Painting', trade: 'painting', tags: ['painting', 'interior', 'walls'] },
  availability: { residential: true, commercial: true, emergencyEligible: false, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 5, typical: 9, maximum: 16 }, quantityUnit: 'squareFoot', setupHours: 1, cleanupHours: 1, productionRate: { quantity: 400, unit: 'squareFoot', laborHours: 4, unitsPerTechnicianHour: { minimum: 60, typical: 100, maximum: 150 } }, returnVisits: { minimum: 1, typical: 2, maximum: 3 } },
  materials: { costRange: { minimum: 90, typical: 220, maximum: 475 }, costUnit: 'typicalProject', typicalMaterials: ['Interior paint', 'Primer when required', 'Caulk', 'Patch compound', 'Sanding materials', 'Masking materials', 'Floor and furniture protection', 'Roller covers and disposable supplies'], wasteFactorPercentage: 12, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: { typicalEquipment: ['Painting tools', 'Ladders', 'Surface protection'], rentalMayBeRequired: true, rentalCostRange: { minimum: 0, typical: 75, maximum: 350 }, elevatedAccessPossible: true, specialtyEquipmentNotes: ['Stairwells and high ceilings require access review.'] },
  timeline: { onsiteLaborHours: { minimum: 5, typical: 9, maximum: 16 }, calendarDurationDays: { minimum: 1, typical: 2, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, dryingOrCuringTimeHours: { minimum: 2, typical: 4, maximum: 8 }, returnVisitRequired: true, weatherSensitive: false, permitMayAffectTimeline: false },
  pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 12 },
  estimatorQuestions: [question('roomCount', 'Room count', 'number', ['labor', 'materials', 'timeline'], true), question('wallDimensions', 'Wall dimensions', 'measurement', ['labor', 'materials', 'confidence'], true), question('ceilingHeightFeet', 'Ceiling height', 'measurement', ['labor', 'equipment']), question('surfacesIncluded', 'Walls, ceilings, trim, or doors', 'multiSelect', ['labor', 'materials', 'scope'], true), question('colorCount', 'Number of colors', 'number', ['labor', 'materials']), question('existingCondition', 'Existing condition', 'singleSelect', ['labor', 'materials']), question('repairsRequired', 'Repairs required', 'boolean', ['labor', 'scope']), question('occupied', 'Occupied or vacant', 'boolean', ['labor', 'timeline']), question('furnitureMovement', 'Furniture movement', 'boolean', ['labor', 'scope']), question('customerSuppliedMaterials', 'Paint supplied by customer', 'boolean', ['materials', 'recommendations']), question('majorColorChange', 'Color change severity', 'boolean', ['labor', 'materials']), question('photos', 'Photos', 'photo', ['confidence'])],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, ...ELEVATED_WORK_MODIFIERS, { id: 'paint-ceilings', name: 'Ceilings included', description: 'Ceiling painting adjustment.', conditions: [{ field: 'surfacesIncluded', operator: 'includes', value: 'ceilings' }], effects: { laborMultiplier: 1.275, scopeStepsToAdd: ['Prepare and paint included ceiling surfaces.'] }, customerExplanation: 'Ceiling painting requires additional preparation and application time.', internalNotes: ['Approved planning band is 20%–35%; typical adjustment used.'] }, { id: 'paint-trim', name: 'Trim included', description: 'Trim painting adjustment.', conditions: [{ field: 'surfacesIncluded', operator: 'includes', value: 'trim' }], effects: { laborMultiplier: 1.225, scopeStepsToAdd: ['Prepare and paint included trim.'] }, customerExplanation: 'Trim painting adds detailed preparation and application time.', internalNotes: ['Approved planning band is 15%–30%; typical adjustment used.'] }, { id: 'paint-color-change', name: 'Major color change', description: 'Major color change adjustment.', conditions: [{ field: 'majorColorChange', operator: 'equals', value: true }], effects: { laborMultiplier: 1.15, materialMultiplier: 1.15 }, customerExplanation: 'A major color change may require additional coating coverage.', internalNotes: [] }, { id: 'paint-heavy-patching', name: 'Heavy patching', description: 'Heavy surface repair adjustment.', conditions: [{ field: 'heavyPatching', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2, scopeStepsToAdd: ['Repair included accessible surface defects before painting.'] }, customerExplanation: 'Heavy patching adds surface preparation.', internalNotes: [] }, { id: 'paint-occupied-contents', name: 'Occupied with significant contents', description: 'Protection and contents coordination adjustment.', conditions: [{ field: 'occupied', operator: 'equals', value: true }, { field: 'furnitureMovement', operator: 'equals', value: true }], effects: { laborMultiplier: 1.1, scopeStepsToAdd: ['Coordinate furniture movement and protect occupied areas.'] }, customerExplanation: 'Significant contents require additional protection and staging.', internalNotes: [] }, { id: 'paint-specialty-review', name: 'Specialty painting review', description: 'Specialty surfaces or access require review.', conditions: [{ field: 'specialtyPainting', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Specialty coatings or surfaces require direct review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Wall measurements', 'Surface list', 'Color information', 'Photos'], reducesConfidence: ['Unknown surface condition', 'Missing measurements', 'Missing photos'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Inspect visible paint surfaces.', 'Protect floors and adjacent finishes.', 'Prepare accessible surfaces.', 'Mask included edges and fixtures.', 'Apply included primer and paint coats.'], conditionalSteps: ['Repair included minor surface defects.', 'Caulk included trim gaps.', 'Evaluate specialty coatings before work.'], cleanupSteps: ['Remove masking and disposable protection.', 'Clean the work area.'] },
  recommendations: { relatedServices: ['Drywall repair', 'Baseboard and trim repair'], customerPreparation: ['Confirm selected colors and sheen.', 'Remove fragile and personal items from work areas.'], professionalReviewTriggers: ['Cabinets', 'Specialty coatings', 'Stairwells', 'Height over 12 feet'] },
  assumptions: ['Base project represents one average room or approximately 300–500 square feet of paintable wall surface.'],
  exclusions: ['Cabinet refinishing', 'Lead-paint disturbance', 'Specialty coating systems unless reviewed'],
  permitsAndCode: { permitMayBeRequired: false, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: false, notes: ['Lead-paint possibility requires appropriate review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
