import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, ELEVATED_WORK_MODIFIERS, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const ceilingTileReplacement = {
  identity: { id: 'ceiling-tile-replacement', slug: 'ceiling-tile-replacement', version: '1.0.0', name: 'Ceiling Tile Replacement', shortName: 'Ceiling Tile Replacement', description: 'Replace panels in an existing accessible suspension grid.', category: 'Property Maintenance', trade: 'general repair', tags: ['ceiling tile', 'commercial maintenance', 'suspension grid'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 1, typical: 2, maximum: 6 }, quantityUnit: 'item', setupHours: 0.5, cleanupHours: 0.5, productionRate: { quantity: 5, unit: 'tile', laborHours: 1, unitsPerTechnicianHour: { minimum: 2, typical: 5, maximum: 10 } }, returnVisits: { minimum: 1, typical: 1, maximum: 2 } },
  materials: { costRange: { minimum: 10, typical: 25, maximum: 65 }, costUnit: 'perItem', typicalMaterials: ['Matching ceiling panels', 'Minor grid fasteners', 'Cutting consumables', 'Surface protection materials'], wasteFactorPercentage: 10, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: { typicalEquipment: ['Ceiling-tile cutting tools', 'Ladders', 'Surface protection'], rentalMayBeRequired: true, rentalCostRange: { minimum: 0, typical: 125, maximum: 750 }, elevatedAccessPossible: true, specialtyEquipmentNotes: ['Scaffold or lift review may be required for ceilings above ten feet.'] },
  timeline: { onsiteLaborHours: { minimum: 1, typical: 2, maximum: 6 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 5, maximum: 30 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: true },
  pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 10 },
  estimatorQuestions: [question('tileQuantity', 'Tile quantity', 'number', ['labor', 'materials'], true), question('tileDimensions', 'Tile dimensions', 'measurement', ['materials', 'confidence'], true), question('edgeProfile', 'Edge profile', 'text', ['materials', 'confidence']), question('manufacturerModel', 'Manufacturer or model', 'text', ['materials', 'timeline']), question('matchingTileAvailable', 'Matching tile available', 'boolean', ['confidence', 'materials']), question('ceilingHeightFeet', 'Ceiling height', 'measurement', ['labor', 'equipment', 'manualReview'], true), question('gridDamage', 'Grid damage', 'boolean', ['labor', 'manualReview']), question('fixturesNearby', 'Fixtures or diffusers nearby', 'boolean', ['labor', 'manualReview']), question('waterStaining', 'Water staining', 'boolean', ['manualReview']), question('occupied', 'Occupied facility', 'boolean', ['labor', 'timeline']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, ...ELEVATED_WORK_MODIFIERS, { id: 'tile-fixture-cutting', name: 'Tile cutting around fixtures', description: 'Fixture cutting adjustment.', conditions: [{ field: 'fixturesNearby', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2, scopeStepsToAdd: ['Cut included panels around accessible existing fixtures or diffusers.'] }, customerExplanation: 'Cutting panels around fixtures requires additional fitting.', internalNotes: [] }, { id: 'tile-grid-repair', name: 'Ceiling grid repair', description: 'Grid repair allowance and review.', conditions: [{ field: 'gridDamage', operator: 'equals', value: true }], effects: { flatLaborHours: 3, requiresManualReview: true, scopeStepsToAdd: ['Evaluate and repair accessible included minor grid damage.'] }, customerExplanation: 'Grid damage requires direct extent review.', internalNotes: ['Approved planning addition is one to five hours; typical three-hour addition used.'] }, { id: 'tile-occupied-commercial', name: 'Occupied commercial facility', description: 'Staged access and protection adjustment.', conditions: [{ field: 'propertyContext', operator: 'equals', value: 'commercial' }, { field: 'occupied', operator: 'equals', value: true }, { field: 'occupancyAffectsWork', operator: 'equals', value: true }], effects: { laborMultiplier: 1.05, scopeStepsToAdd: ['Coordinate staged access and protect occupied facility areas.'] }, customerExplanation: 'Occupied facilities may require staged access and protection.', internalNotes: [] }, { id: 'tile-water-stain', name: 'Water-stained ceiling tile', description: 'Water staining requires source review.', conditions: [{ field: 'waterStaining', operator: 'equals', value: true }], effects: { requiresManualReview: true, recommendationsToAdd: ['Confirm the moisture source is resolved before replacing stained panels.'] }, customerExplanation: 'Water staining requires source verification.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Tile quantity', 'Dimensions', 'Manufacturer or model', 'Ceiling height', 'Photos'], reducesConfidence: ['Unknown tile match', 'Water staining', 'Unknown grid condition'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Inspect visible panels and accessible suspension grid.', 'Protect the work area.', 'Remove included damaged panels.', 'Measure and cut included replacement panels.', 'Install replacement panels in the existing accessible grid.'], conditionalSteps: ['Evaluate visible water staining before replacement.', 'Evaluate accessible grid damage.', 'Coordinate around existing fixtures without altering regulated systems.'], cleanupSteps: ['Clean the work area.', 'Remove included panel debris.'] },
  recommendations: { relatedServices: ['Drywall repair', 'Commercial maintenance'], customerPreparation: ['Provide manufacturer, model, edge profile, or a sample tile when available.'], professionalReviewTriggers: ['Active leak', 'Mold-like growth', 'Asbestos possibility', 'Fire-rated ceiling system', 'Full grid installation', 'Seismic-grid requirements', 'Height above 16 feet', 'Electrical or mechanical work required'] },
  assumptions: ['Existing suspension grid is accessible and generally serviceable.', 'Profile excludes full suspended-ceiling installation.'], exclusions: ['Full grid installation', 'Electrical or mechanical relocation', 'Asbestos testing or abatement', 'Moisture-source repair'],
  permitsAndCode: { permitMayBeRequired: true, inspectionMayBeRequired: true, licensedTradeMayBeRequired: true, jurisdictionReviewRequired: true, notes: ['Fire-rated, seismic, electrical, and mechanical conditions require appropriate review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
