import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, ELEVATED_WORK_MODIFIERS, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_EQUIPMENT, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const generalHandymanRepair = {
  identity: { id: 'general-handyman-repair', slug: 'general-handyman-repair', version: '1.0.0', name: 'General Handyman Repair', shortName: 'General Handyman Repair', description: 'Complete small, clearly described, accessible, non-regulated repair tasks.', category: 'Property Maintenance', trade: 'general repair', tags: ['handyman', 'minor repair', 'maintenance'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 1, typical: 3, maximum: 8 }, quantityUnit: 'task', setupHours: 0.25, cleanupHours: 0.5, productionRate: { quantity: 1, unit: 'task', laborHours: 3 }, returnVisits: { minimum: 1, typical: 1, maximum: 2 } },
  materials: { costRange: { minimum: 0, typical: 75, maximum: 350 }, costUnit: 'typicalProject', typicalMaterials: ['Service-specific minor repair materials', 'Fasteners', 'Consumables', 'Surface protection'], wasteFactorPercentage: 10, customerSuppliedAllowed: true, materialPickupUsuallyRequired: false, specialOrderPossible: true },
  equipment: { ...STANDARD_EQUIPMENT, elevatedAccessPossible: true },
  timeline: { onsiteLaborHours: { minimum: 1, typical: 3, maximum: 8 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: true },
  pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 10 },
  estimatorQuestions: [question('detailedDescription', 'Detailed description', 'textarea', ['scope', 'confidence', 'manualReview'], true), question('taskCount', 'Number of tasks', 'number', ['labor', 'confidence'], true), question('measurements', 'Measurements', 'measurement', ['labor', 'materials', 'confidence']), question('customerSuppliedMaterials', 'Materials supplied', 'boolean', ['materials', 'recommendations']), question('interiorOrExterior', 'Interior or exterior', 'singleSelect', ['scope', 'timeline']), question('ceilingHeightFeet', 'Height', 'measurement', ['labor', 'equipment', 'manualReview']), question('photos', 'Photos', 'photo', ['confidence'], true), question('regulatedWorkInvolved', 'Is plumbing, electrical, HVAC, structural, roofing, gas, or hazardous material involved', 'boolean', ['manualReview'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, ...ELEVATED_WORK_MODIFIERS, { id: 'handyman-many-tasks', name: 'More than five unrelated tasks', description: 'Broad multi-task scope requires review.', conditions: [{ field: 'taskCount', operator: 'greaterThan', value: 5 }], effects: { requiresManualReview: true, recommendationsToAdd: ['Separate unrelated tasks into a reviewed scope before final pricing.'] }, customerExplanation: 'More than five unrelated tasks require direct scope review.', internalNotes: [] }, { id: 'handyman-regulated', name: 'Regulated or hazardous work', description: 'Regulated work is outside the general handyman profile.', conditions: [{ field: 'regulatedWorkInvolved', operator: 'equals', value: true }], effects: { requiresManualReview: true, confidenceAdjustment: -15, recommendationsToAdd: ['Arrange review by the appropriate qualified trade before work.'] }, customerExplanation: 'Licensed, structural, roofing, gas, or hazardous work requires separate review.', internalNotes: [] }, { id: 'handyman-incomplete', name: 'Incomplete project description', description: 'Incomplete scope requires review.', conditions: [{ field: 'descriptionLength', operator: 'lessThan', value: 100 }], effects: { requiresManualReview: true, confidenceAdjustment: -10, recommendationsToAdd: ['Provide a detailed description and photos of every requested task.'] }, customerExplanation: 'A detailed scope is needed before final pricing.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Detailed description', 'Task count', 'Measurements', 'Photos'], reducesConfidence: ['Incomplete description', 'Missing photos', 'Unrelated tasks', 'Regulated work'], requiredForStrongConfidence: ['detailedDescription', 'photos'] },
  scopeOfWork: { standardSteps: ['Review the clearly described included tasks.', 'Inspect visible accessible conditions.', 'Protect adjacent surfaces.', 'Prepare and repair included non-regulated items.', 'Test normal operation of included repaired items.'], conditionalSteps: ['Evaluate whether a qualified trade, permit, or specialized review is required.', 'Document visible conditions that fall outside the included scope.'], cleanupSteps: ['Clean included work areas.', 'Remove included minor repair debris.'] },
  recommendations: { relatedServices: ['Drywall repair', 'Baseboard and trim repair', 'Door repair'], customerPreparation: ['Provide a detailed description, measurements, and photos for each task.', 'Identify customer-supplied materials before scheduling.'], professionalReviewTriggers: ['More than five unrelated tasks', 'Structural work', 'Roofing', 'Gas piping', 'Panel or circuit work', 'Refrigerant work', 'Permit-required work', 'Hazardous materials', 'Active water damage', 'Work above 16 feet', 'Incomplete project description'] },
  assumptions: ['All included tasks are small, clearly described, accessible, and non-regulated.'], exclusions: ['Structural work', 'Roofing', 'Gas piping', 'Electrical panel or circuit work', 'Refrigerant work', 'Hazardous-material work', 'Poorly defined or concealed work'],
  permitsAndCode: { permitMayBeRequired: true, inspectionMayBeRequired: true, licensedTradeMayBeRequired: true, jurisdictionReviewRequired: true, notes: ['Regulated or permit-required work must be separated for appropriate review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
