import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_EQUIPMENT, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const lockChange = {
  identity: { id: 'lock-change', slug: 'lock-change', version: '1.0.0', name: 'Lock Change', shortName: 'Lock Change', description: 'Replace standard accessible locksets and included deadbolts.', category: 'Property Maintenance', trade: 'general repair', tags: ['locks', 'hardware', 'doors'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 1, typical: 1.5, maximum: 3 }, quantityUnit: 'item', setupHours: 0.25, cleanupHours: 0.25, productionRate: { quantity: 1, unit: 'lockset', laborHours: 1, unitsPerTechnicianHour: { minimum: 1, typical: 2, maximum: 3 } }, returnVisits: { minimum: 1, typical: 1, maximum: 2 } },
  materials: { costRange: { minimum: 25, typical: 85, maximum: 300 }, costUnit: 'perItem', typicalMaterials: ['Standard lockset', 'Deadbolt when included', 'Fasteners', 'Minor door-preparation materials'], wasteFactorPercentage: 0, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: STANDARD_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 1.5, maximum: 3 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 2 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 2, maximum: 14 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: false },
  pricing: STANDARD_PRICING,
  estimatorQuestions: [question('lockCount', 'Number of locks', 'number', ['labor', 'materials'], true), question('interiorOrExterior', 'Interior or exterior', 'singleSelect', ['scope']), question('existingBorePrepared', 'Existing bore preparation', 'boolean', ['labor']), question('deadboltIncluded', 'Deadbolt included', 'boolean', ['labor', 'materials']), question('keyedAlike', 'Keyed alike', 'boolean', ['materials', 'recommendations']), question('smartLock', 'Smart lock', 'boolean', ['labor', 'materials']), question('commercialHardware', 'Commercial hardware', 'boolean', ['manualReview']), question('doorCondition', 'Door condition', 'singleSelect', ['labor', 'manualReview']), question('customerSuppliedMaterials', 'Customer supplying hardware', 'boolean', ['materials', 'recommendations']), question('photos', 'Photos', 'photo', ['confidence'])],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, { id: 'lock-smart', name: 'Smart lock', description: 'Smart-lock installation adjustment.', conditions: [{ field: 'smartLock', operator: 'equals', value: true }], effects: { flatLaborHours: 1, recommendationsToAdd: ['Confirm smart-lock compatibility and customer-provided access credentials.'] }, customerExplanation: 'Smart locks require additional setup and testing.', internalNotes: ['Approved planning addition is 0.5–2 hours; typical one-hour addition used.'] }, { id: 'lock-new-bore', name: 'New bore preparation', description: 'New bore preparation adjustment.', conditions: [{ field: 'existingBorePrepared', operator: 'equals', value: false }], effects: { flatLaborHours: 1, scopeStepsToAdd: ['Prepare a standard included bore where the door is suitable.'] }, customerExplanation: 'New bore preparation adds fitting time.', internalNotes: ['Approved planning addition is 0.5–1.5 hours; typical one-hour addition used.'] }, { id: 'lock-commercial-specialty', name: 'Commercial specialty hardware', description: 'Commercial specialty hardware requires review.', conditions: [{ field: 'commercialHardware', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Commercial mortise, panic, access-control, or master-key systems require direct review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Lock quantity', 'Hardware type', 'Door condition', 'Photos'], reducesConfidence: ['Unknown door preparation', 'Specialty commercial hardware'], requiredForStrongConfidence: ['photos'] },
  scopeOfWork: { standardSteps: ['Inspect visible door and existing hardware.', 'Remove included standard lock hardware.', 'Install included compatible lockset or deadbolt.', 'Adjust accessible strike alignment.', 'Test normal lock and latch operation.'], conditionalSteps: ['Prepare a standard bore where included and suitable.', 'Configure included smart-lock functions provided by the manufacturer.'], cleanupSteps: ['Clean the work area.', 'Remove included packaging and replaced hardware debris.'] },
  recommendations: { relatedServices: ['Interior door repair or replacement', 'Exterior door repair or replacement'], customerPreparation: ['Confirm hardware selection, finish, keying, and access requirements.'], professionalReviewTriggers: ['Commercial mortise lock', 'Panic hardware', 'Access control', 'Master keying'] },
  assumptions: ['Door and frame are suitable for the selected standard hardware.'], exclusions: ['Access-control wiring', 'Master-key system design', 'Door or frame reconstruction'],
  permitsAndCode: { permitMayBeRequired: false, inspectionMayBeRequired: false, licensedTradeMayBeRequired: true, jurisdictionReviewRequired: true, notes: ['Confirm locksmith licensing or regulated hardware requirements where applicable.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
