import type { ServiceModifier } from '../../templates/serviceModifierTemplate'

export const FLOORING_MODIFIERS: readonly ServiceModifier[] = [
  { id: 'flooring-floating-removal', name: 'Existing floating floor removal', description: 'Remove included floating flooring.', conditions: [{ field: 'existingFlooringRemovalRequired', operator: 'equals', value: true }, { field: 'existingFlooringType', operator: 'equals', value: 'floating' }], effects: { laborHoursPerUnit: { minimum: 0.03, typical: 0.045, maximum: 0.06 }, laborUnitField: 'squareFeet', scopeStepsToAdd: ['Remove included existing floating flooring.'] }, customerExplanation: 'The range includes removal of the selected floating floor.', internalNotes: [] },
  { id: 'flooring-sheet-carpet-removal', name: 'Sheet vinyl or carpet removal', description: 'Remove included sheet vinyl or carpet.', conditions: [{ field: 'existingFlooringRemovalRequired', operator: 'equals', value: true }, { field: 'existingFlooringType', operator: 'includes', value: 'sheet-or-carpet' }], effects: { laborHoursPerUnit: { minimum: 0.04, typical: 0.06, maximum: 0.08 }, laborUnitField: 'squareFeet', scopeStepsToAdd: ['Remove included sheet vinyl or carpet.'] }, customerExplanation: 'The range includes selected sheet vinyl or carpet removal.', internalNotes: [] },
  { id: 'flooring-glued-removal', name: 'Glued flooring removal', description: 'Glued flooring removal requires additional labor and review.', conditions: [{ field: 'existingFlooringRemovalRequired', operator: 'equals', value: true }, { field: 'existingFlooringType', operator: 'equals', value: 'glued' }], effects: { laborMultiplierRange: { minimum: 1.3, typical: 1.45, maximum: 1.6 }, requiresManualReview: true, scopeStepsToAdd: ['Remove included glued flooring where accessible.'] }, customerExplanation: 'Glued flooring removal depends on adhesive and substrate conditions.', internalNotes: [] },
  { id: 'flooring-minor-patching', name: 'Minor floor patching', description: 'Minor accessible floor patching.', conditions: [{ field: 'subfloorPreparation', operator: 'equals', value: 'minor-patching' }], effects: { flatLaborHoursRange: { minimum: 1, typical: 2, maximum: 4 }, flatMaterialCostRange: { minimum: 25, typical: 75, maximum: 150 }, scopeStepsToAdd: ['Complete included minor substrate patching.'] }, customerExplanation: 'Minor substrate patching is included in the planning range.', internalNotes: [] },
  { id: 'flooring-moderate-leveling', name: 'Moderate floor leveling', description: 'Moderate leveling allowance.', conditions: [{ field: 'subfloorPreparation', operator: 'equals', value: 'moderate-leveling' }], effects: { flatLaborHoursRange: { minimum: 4, typical: 8, maximum: 12 }, flatMaterialCostRange: { minimum: 100, typical: 300, maximum: 600 }, requiresManualReview: true, scopeStepsToAdd: ['Complete reviewed moderate leveling where included.'] }, customerExplanation: 'Moderate leveling requires direct substrate review.', internalNotes: [] },
  { id: 'flooring-appliance-movement', name: 'Appliance movement', description: 'Move and reset included appliances.', conditions: [{ field: 'applianceCount', operator: 'greaterThan', value: 0 }], effects: { laborHoursPerUnit: { minimum: 0.5, typical: 1, maximum: 1.5 }, laborUnitField: 'applianceCount', scopeStepsToAdd: ['Move and reinstall included appliances without regulated disconnection.'] }, customerExplanation: 'Included appliances require additional handling.', internalNotes: [] },
  { id: 'flooring-baseboard-reset', name: 'Baseboard removal and reset', description: 'Remove and reset included baseboard.', conditions: [{ field: 'baseboardRemovalReset', operator: 'equals', value: true }], effects: { laborHoursPerUnit: { minimum: 0.04, typical: 0.06, maximum: 0.08 }, laborUnitField: 'baseboardLinearFeet', scopeStepsToAdd: ['Remove and reset included reusable baseboard.'] }, customerExplanation: 'Selected baseboard removal and reset is included.', internalNotes: [] },
  { id: 'flooring-new-baseboard', name: 'New baseboard requested', description: 'New baseboard is a related service unless separately included.', conditions: [{ field: 'newBaseboardsRequired', operator: 'equals', value: true }], effects: { recommendationsToAdd: ['Review Baseboard and Trim Repair as a related service; new baseboard is not included unless separately selected.'] }, customerExplanation: 'New baseboard requires a separate included scope.', internalNotes: [] },
  { id: 'flooring-complex-layout', name: 'Complex flooring layout', description: 'Complex layout or many doorways.', conditions: [{ field: 'complexLayout', operator: 'equals', value: true }], effects: { laborMultiplier: 1.15 }, customerExplanation: 'Complex layouts and doorways require additional layout and cutting.', internalNotes: [] },
  { id: 'flooring-occupied-furnished', name: 'Occupied furnished rooms', description: 'Contents require staged access.', conditions: [{ field: 'occupied', operator: 'equals', value: true }, { field: 'furniturePresent', operator: 'equals', value: true }], effects: { laborMultiplier: 1.1, scopeStepsToAdd: ['Coordinate staged contents and protect occupied rooms.'] }, customerExplanation: 'Furnished rooms require staged access and protection.', internalNotes: [] },
  { id: 'flooring-commercial-phased', name: 'Commercial occupied area', description: 'Commercial phased access or protection.', conditions: [{ field: 'propertyContext', operator: 'equals', value: 'commercial' }, { field: 'occupied', operator: 'equals', value: true }, { field: 'occupancyAffectsWork', operator: 'equals', value: true }], effects: { laborMultiplier: 1.1, requiresManualReview: true }, customerExplanation: 'Occupied commercial work may require shutdown or phased access planning.', internalNotes: [] },
  { id: 'flooring-stairs', name: 'Flooring on stairs', description: 'Stair installation requires manual review.', conditions: [{ field: 'stairsIncluded', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Stair installation requires direct layout and product review.', internalNotes: [] },
  { id: 'flooring-moisture', name: 'Active flooring moisture concern', description: 'Active moisture requires manual review.', conditions: [{ field: 'activeMoisture', operator: 'equals', value: true }], effects: { requiresManualReview: true, recommendationsToAdd: ['Resolve and document the active moisture source before flooring installation.'] }, customerExplanation: 'Active moisture must be resolved before installation.', internalNotes: [] },
  { id: 'flooring-structural-subfloor', name: 'Structural subfloor concern', description: 'Suspected structural subfloor damage.', conditions: [{ field: 'structuralSubfloorDamage', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Structural subfloor conditions require separate review.', internalNotes: [] },
  { id: 'flooring-hazardous-material', name: 'Possible asbestos flooring or adhesive', description: 'Potential regulated material.', conditions: [{ field: 'hazardousFlooringPossible', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Potential asbestos-containing material requires appropriate evaluation.', internalNotes: [] },
]

export const FLOORING_MANUAL_REVIEW_TRIGGERS = ['Stairs', 'Structural subfloor damage', 'Active moisture', 'Visible mold-like growth', 'Suspected asbestos flooring or adhesive', 'More than 1,500 square feet', 'Extensive leveling', 'Multiple occupied commercial phases', 'Heavy equipment relocation', 'Floor drains', 'Commercial kitchens', 'Medical environments', 'Unknown product installation requirements'] as const

export const FLOORING_SCOPE_STEPS = ['Confirm project area and flooring product.', 'Protect adjacent finishes.', 'Remove included existing flooring where selected.', 'Inspect visible substrate condition.', 'Complete included minor substrate preparation.', 'Plan plank layout.', 'Maintain manufacturer-required perimeter clearances.', 'Install flooring.', 'Install included transitions and accessories.', 'Reinstall included appliances where selected.', 'Complete included trim work.', 'Inspect the finished surface.'] as const

export const FLOORING_CLEANUP_STEPS = ['Remove included debris.', 'Clean the work area.'] as const
