import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'
import { FLOORING_CLEANUP_STEPS, FLOORING_MANUAL_REVIEW_TRIGGERS, FLOORING_MODIFIERS, FLOORING_SCOPE_STEPS } from './flooringShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const laminateFlooring = {
  identity: { id: 'laminate-flooring', slug: 'laminate-flooring', version: '1.0.0', name: 'Laminate Flooring', shortName: 'Laminate Flooring', description: 'Install floating click-lock laminate over a clean, flat, suitable substrate.', category: 'Flooring', trade: 'flooring', tags: ['laminate', 'floating floor', 'flooring installation'] },
  availability: { residential: true, commercial: true, emergencyEligible: false, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 7, typical: 16, maximum: 36 }, quantityUnit: 'squareFoot', setupHours: 1, cleanupHours: 1, productionRate: { quantity: 300, unit: 'squareFoot', laborHours: 11, unitsPerTechnicianHour: { minimum: 16, typical: 28, maximum: 40 } }, returnVisits: { minimum: 1, typical: 1, maximum: 2 }, minimumBillableHoursOverride: 4 },
  materials: { costRange: { minimum: 50, typical: 175, maximum: 550 }, costUnit: 'typicalProject', costComponents: [{ name: 'Laminate flooring', costRange: { minimum: 1.75, typical: 3.5, maximum: 7 }, costUnit: 'perSquareFoot', customerSuppliedEligible: true, applyWasteFactor: true }, { name: 'Accessories and consumables', costRange: { minimum: 50, typical: 175, maximum: 550 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false }], typicalMaterials: ['Laminate flooring', 'Manufacturer-approved underlayment', 'Moisture barrier where required', 'Expansion spacers', 'Transitions', 'Reducers', 'Matching trim accessories', 'Patch compound', 'Protection materials'], wasteFactorPercentage: 10, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: { typicalEquipment: ['Project-specific flooring cutting and disposal equipment when required'], rentalMayBeRequired: true, rentalCostRange: { minimum: 0, typical: 75, maximum: 400 }, elevatedAccessPossible: false, specialtyEquipmentNotes: ['Ordinary hand tools are not customer equipment charges.'] },
  timeline: { onsiteLaborHours: { minimum: 7, typical: 16, maximum: 36 }, calendarDurationDays: { minimum: 1, typical: 3, maximum: 5 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 5, maximum: 14 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: false },
  pricing: { ...STANDARD_PRICING, minimumLaborHoursOverride: 4, wasteFactorPercentage: 10 },
  estimatorQuestions: [question('squareFeet', 'Total square footage', 'measurement', ['labor', 'materials', 'confidence'], true), question('roomDimensions', 'Room dimensions', 'measurement', ['labor', 'confidence'], true), question('roomCount', 'Number of rooms', 'number', ['labor', 'timeline']), question('existingFlooringType', 'Existing flooring type', 'singleSelect', ['labor', 'scope']), question('existingFlooringRemovalRequired', 'Existing flooring removal required', 'boolean', ['labor', 'scope']), question('subfloorType', 'Subfloor type', 'text', ['scope']), question('subfloorCondition', 'Subfloor condition', 'singleSelect', ['labor', 'manualReview'], true), question('subfloorPreparation', 'Floor-leveling concerns', 'singleSelect', ['labor', 'materials', 'manualReview']), question('activeMoisture', 'Moisture concerns', 'boolean', ['manualReview']), question('applianceCount', 'Appliances present', 'number', ['labor']), question('furniturePresent', 'Furniture present', 'boolean', ['labor']), question('baseboardRemovalReset', 'Baseboards being removed', 'boolean', ['labor']), question('newBaseboardsRequired', 'New baseboards required', 'boolean', ['recommendations']), question('quarterRoundRequired', 'Quarter round required', 'boolean', ['labor', 'materials']), question('transitionCount', 'Number of transitions', 'number', ['labor', 'materials']), question('stairsIncluded', 'Stairs included', 'boolean', ['manualReview']), question('occupied', 'Occupied or vacant', 'boolean', ['labor']), question('customerSuppliedMaterials', 'Customer supplying flooring', 'boolean', ['materials']), question('productModel', 'Product manufacturer and model', 'text', ['confidence', 'manualReview']), question('photos', 'Photos', 'photo', ['confidence'], true), question('acclimationRequired', 'Manufacturer acclimation requirement', 'boolean', ['timeline']), question('belowGrade', 'Installation below grade', 'boolean', ['manualReview']), question('wetAreaExposure', 'Wet-area exposure', 'boolean', ['manualReview']), question('attachedUnderlayment', 'Attached underlayment', 'boolean', ['materials']), question('expansionBreakReview', 'Expansion-transition requirements', 'boolean', ['manualReview'])],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, ...FLOORING_MODIFIERS, { id: 'laminate-acclimation', name: 'Product acclimation required', description: 'Manufacturer acclimation adds calendar time.', conditions: [{ field: 'acclimationRequired', operator: 'equals', value: true }], effects: { calendarDaysToAdd: { minimum: 1, typical: 2, maximum: 3 } }, customerExplanation: 'Required acclimation may extend calendar duration without adding technician labor.', internalNotes: [] }, { id: 'laminate-wet-area', name: 'Wet-area laminate review', description: 'Wet-area suitability requires review.', conditions: [{ field: 'wetAreaExposure', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Manufacturer suitability must be confirmed for wet-area exposure.', internalNotes: [] }, { id: 'laminate-expansion', name: 'Long continuous run', description: 'Expansion-break requirements require review.', conditions: [{ field: 'expansionBreakReview', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Long continuous runs require manufacturer expansion review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Square footage', 'Product model', 'Subfloor details', 'Acclimation requirements', 'Photos'], reducesConfidence: ['Unknown manufacturer requirements', 'Wet-area exposure', 'Below-grade moisture concerns'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: [...FLOORING_SCOPE_STEPS, 'Verify required expansion clearances.', 'Verify underlayment and moisture-control requirements.', 'Install manufacturer-compatible transitions.'], conditionalSteps: ['Avoid fastening floating flooring through the finished field unless the product requires it.', 'Evaluate wet-area and below-grade product suitability.'], cleanupSteps: FLOORING_CLEANUP_STEPS },
  recommendations: { relatedServices: ['Baseboard and Trim Repair'], customerPreparation: ['Confirm manufacturer acclimation and installation requirements.'], professionalReviewTriggers: [...FLOORING_MANUAL_REVIEW_TRIGGERS, 'Wet rooms', 'Below-grade moisture concerns', 'Product unsuitable for location', 'Long continuous runs'] },
  assumptions: ['Subfloor is structurally sound.', 'Selected laminate is suitable for the location.', 'Major leveling and moisture remediation are excluded unless selected.'],
  exclusions: ['Structural subfloor replacement', 'Moisture remediation', 'Hazardous-material abatement', 'Stairs unless reviewed', 'Major furniture moving unless included'],
  permitsAndCode: { permitMayBeRequired: false, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: false, notes: ['Product-specific moisture and expansion requirements must be confirmed.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
