import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'
import { FLOORING_CLEANUP_STEPS, FLOORING_MANUAL_REVIEW_TRIGGERS, FLOORING_MODIFIERS, FLOORING_SCOPE_STEPS } from './flooringShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const luxuryVinylPlankFlooring = {
  identity: { id: 'luxury-vinyl-plank-flooring', slug: 'luxury-vinyl-plank-flooring', version: '1.0.0', name: 'Luxury Vinyl Plank Flooring', shortName: 'LVP Flooring', description: 'Install floating click-lock luxury vinyl plank over a clean, dry, flat, suitable substrate.', category: 'Flooring', trade: 'flooring', tags: ['LVP', 'floating floor', 'flooring installation'] },
  availability: { residential: true, commercial: true, emergencyEligible: false, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 6, typical: 14, maximum: 32 }, quantityUnit: 'squareFoot', setupHours: 1, cleanupHours: 1, productionRate: { quantity: 300, unit: 'squareFoot', laborHours: 10, unitsPerTechnicianHour: { minimum: 18, typical: 30, maximum: 45 } }, returnVisits: { minimum: 1, typical: 1, maximum: 2 }, minimumBillableHoursOverride: 4 },
  materials: { costRange: { minimum: 40, typical: 150, maximum: 500 }, costUnit: 'typicalProject', costComponents: [{ name: 'Luxury vinyl plank', costRange: { minimum: 2, typical: 4, maximum: 8 }, costUnit: 'perSquareFoot', customerSuppliedEligible: true, applyWasteFactor: true }, { name: 'Installation consumables and accessories', costRange: { minimum: 40, typical: 150, maximum: 500 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false }], typicalMaterials: ['Luxury vinyl plank', 'Underlayment when required', 'Moisture barrier when required', 'Spacers', 'Transition strips', 'Reducers', 'Stair noses when applicable', 'Adhesive for accessories where required', 'Floor patch compound', 'Replacement trim when included', 'Fasteners', 'Protection materials'], wasteFactorPercentage: 10, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: { typicalEquipment: ['Project-specific flooring cutting and disposal equipment when required'], rentalMayBeRequired: true, rentalCostRange: { minimum: 0, typical: 75, maximum: 400 }, elevatedAccessPossible: false, specialtyEquipmentNotes: ['Ordinary hand tools are not customer equipment charges.'] },
  timeline: { onsiteLaborHours: { minimum: 6, typical: 14, maximum: 32 }, calendarDurationDays: { minimum: 1, typical: 3, maximum: 5 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 5, maximum: 14 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: false },
  pricing: { ...STANDARD_PRICING, minimumLaborHoursOverride: 4, wasteFactorPercentage: 10 },
  estimatorQuestions: [question('squareFeet', 'Total square footage', 'measurement', ['labor', 'materials', 'confidence'], true), question('roomDimensions', 'Room dimensions', 'measurement', ['labor', 'confidence'], true), question('roomCount', 'Number of rooms', 'number', ['labor', 'timeline']), question('existingFlooringType', 'Existing flooring type', 'singleSelect', ['labor', 'scope']), question('existingFlooringRemovalRequired', 'Existing flooring removal required', 'boolean', ['labor', 'scope']), question('subfloorType', 'Subfloor type', 'text', ['scope']), question('subfloorCondition', 'Subfloor condition', 'singleSelect', ['labor', 'manualReview'], true), question('subfloorPreparation', 'Floor-leveling concerns', 'singleSelect', ['labor', 'materials', 'manualReview']), question('activeMoisture', 'Moisture concerns', 'boolean', ['manualReview']), question('applianceCount', 'Appliances present', 'number', ['labor']), question('furniturePresent', 'Furniture present', 'boolean', ['labor']), question('baseboardRemovalReset', 'Baseboards being removed', 'boolean', ['labor', 'scope']), question('newBaseboardsRequired', 'New baseboards required', 'boolean', ['recommendations']), question('quarterRoundRequired', 'Quarter round required', 'boolean', ['labor', 'materials']), question('transitionCount', 'Number of transitions', 'number', ['labor', 'materials']), question('stairsIncluded', 'Stairs included', 'boolean', ['manualReview']), question('occupied', 'Occupied or vacant', 'boolean', ['labor']), question('customerSuppliedMaterials', 'Customer supplying flooring', 'boolean', ['materials']), question('productModel', 'Product manufacturer and model', 'text', ['confidence', 'manualReview']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, ...FLOORING_MODIFIERS],
  confidence: { improvesConfidence: ['Square footage', 'Room dimensions', 'Product model', 'Subfloor details', 'Photos'], reducesConfidence: ['Unknown substrate', 'Unknown product requirements', 'Moisture concerns'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: FLOORING_SCOPE_STEPS, conditionalSteps: ['Evaluate visible moisture and substrate concerns.', 'Install included quarter round and transitions.', 'Coordinate normal appliance handling without unapproved utility disconnection.'], cleanupSteps: FLOORING_CLEANUP_STEPS },
  recommendations: { relatedServices: ['Baseboard and Trim Repair'], customerPreparation: ['Confirm flooring product and manufacturer requirements.', 'Remove small personal items from the installation area.'], professionalReviewTriggers: FLOORING_MANUAL_REVIEW_TRIGGERS },
  assumptions: ['Subfloor is structurally sound.', 'Flooring product is suitable for the property.', 'Installation area is reasonably rectangular.', 'Normal access is available.', 'Major leveling and moisture remediation are excluded unless selected.'],
  exclusions: ['Structural subfloor replacement', 'Moisture remediation', 'Hazardous-material abatement', 'Stair installation unless specifically reviewed', 'Major furniture moving unless included', 'Electrical or plumbing disconnection beyond approved appliance handling'],
  permitsAndCode: { permitMayBeRequired: false, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: false, notes: ['Hazardous-material or structural conditions require separate review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
