import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_EQUIPMENT, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const groutCaulkRepair = {
  identity: { id: 'grout-caulk-repair', slug: 'grout-caulk-repair', version: '1.0.0', name: 'Grout and Caulk Repair', shortName: 'Grout & Caulk Repair', description: 'Remove and replace included failed grout or tile-area sealant in accessible joints.', category: 'Tile', trade: 'tile', tags: ['grout', 'caulk', 'sealant'] },
  availability: { residential: true, commercial: true, emergencyEligible: false, afterHoursEligible: true, active: true }, crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 2, typical: 5, maximum: 12 }, quantityUnit: 'linearFoot', setupHours: 0.5, cleanupHours: 0.75, productionRate: { quantity: 8, unit: 'linearFoot', laborHours: 1, unitsPerTechnicianHour: { minimum: 4, typical: 8, maximum: 15 } }, returnVisits: { minimum: 1, typical: 1, maximum: 2 }, minimumBillableHoursOverride: 2 },
  materials: { costRange: { minimum: 15, typical: 60, maximum: 200 }, costUnit: 'typicalProject', typicalMaterials: ['Matching grout', 'Color-matched tile caulk', 'Silicone sealant where appropriate', 'Backer rod where appropriate', 'Grout-removal consumables', 'Cleaning materials', 'Surface-preparation materials', 'Sealer when included'], wasteFactorPercentage: 15, customerSuppliedAllowed: true, materialPickupUsuallyRequired: false, specialOrderPossible: true },
  equipment: STANDARD_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 2, typical: 5, maximum: 12 }, calendarDurationDays: { minimum: 1, typical: 2, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, dryingOrCuringTimeHours: { minimum: 2, typical: 12, maximum: 48 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: false },
  pricing: { ...STANDARD_PRICING, minimumLaborHoursOverride: 2, wasteFactorPercentage: 15 },
  estimatorQuestions: [question('repairMaterial', 'Grout, caulk, or both', 'singleSelect', ['labor', 'materials'], true), question('linearFeet', 'Approximate linear feet', 'measurement', ['labor', 'confidence'], true), question('surfaceLocation', 'Floor, wall, shower, tub, sink, or countertop', 'singleSelect', ['labor', 'scope']), question('existingCracking', 'Existing cracking', 'boolean', ['scope', 'manualReview']), question('existingStaining', 'Existing staining', 'boolean', ['scope']), question('looseTilePresent', 'Loose tile present', 'boolean', ['manualReview']), question('activeLeak', 'Active leak', 'boolean', ['manualReview']), question('matchingColorRequired', 'Matching color required', 'boolean', ['labor', 'confidence']), question('constantWaterExposure', 'Constant water exposure', 'boolean', ['materials', 'manualReview']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, { id: 'caulk-production-mode', name: 'Caulk removal and replacement', description: 'Caulk work has a higher production rate than grout removal.', conditions: [{ field: 'repairMaterial', operator: 'equals', value: 'caulk' }], effects: { laborMultiplierRange: { minimum: 0.5, typical: 0.55, maximum: 0.6 } }, customerExplanation: 'Caulk-joint work uses a separate production assumption.', internalNotes: ['Caulk removal and replacement: 8–25 linear feet per technician hour.'] }, { id: 'grout-wet-area', name: 'Shower or wet area', description: 'Wet-area labor adjustment.', conditions: [{ field: 'wetArea', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Wet-area preparation requires additional care.', internalNotes: [] }, { id: 'grout-heavy-removal', name: 'Heavy existing sealant removal', description: 'Heavy removal adjustment.', conditions: [{ field: 'heavySealantRemoval', operator: 'equals', value: true }], effects: { laborMultiplier: 1.25 }, customerExplanation: 'Heavy existing sealant requires additional removal time.', internalNotes: [] }, { id: 'grout-deep-wide', name: 'Deep or wide joints', description: 'Deep or wide joint adjustment.', conditions: [{ field: 'deepOrWideJoints', operator: 'equals', value: true }], effects: { laborMultiplier: 1.15, recommendationsToAdd: ['Confirm whether backer rod is required.'] }, customerExplanation: 'Deep or wide joints require additional preparation.', internalNotes: [] }, { id: 'grout-active-leak', name: 'Active leak', description: 'Active leak requires direct review.', conditions: [{ field: 'activeLeak', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'An active leak must be evaluated before finish-joint repair.', internalNotes: [] }, { id: 'grout-loose-tile', name: 'Loose tile present', description: 'Loose tile requires broader review.', conditions: [{ field: 'looseTilePresent', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Loose tile may indicate a broader substrate condition.', internalNotes: [] }, { id: 'grout-constant-water', name: 'Constant water exposure', description: 'Submerged or constant exposure requires product review.', conditions: [{ field: 'constantWaterExposure', operator: 'equals', value: true }], effects: { requiresManualReview: true, recommendationsToAdd: ['Use only a manufacturer-approved product for constant water exposure.'] }, customerExplanation: 'Constant water exposure requires a specifically approved sealant system.', internalNotes: ['Do not default to ordinary acrylic tile caulk.'] }],
  confidence: { improvesConfidence: ['Linear feet', 'Joint type', 'Location', 'Color sample', 'Photos'], reducesConfidence: ['Active leak', 'Loose tile', 'Missing color information'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Protect adjacent surfaces.', 'Remove included failed grout or sealant.', 'Clean and prepare joints.', 'Allow surfaces to dry as required.', 'Install selected grout or sealant.', 'Tool joints to a consistent finish.', 'Clean surrounding surfaces.', 'Communicate cure-time restrictions.'], conditionalSteps: ['Install included backer rod where appropriate.', 'Evaluate visible movement or moisture concerns.'], cleanupSteps: ['Remove included debris.'] },
  recommendations: { relatedServices: ['Tile Repair'], customerPreparation: ['Provide a grout or caulk color sample when matching is required.'], professionalReviewTriggers: ['Active leak', 'Loose tile', 'Failed waterproofing', 'Repeated movement cracks', 'Structural movement', 'Visible microbial growth', 'Constant submerged exposure', 'Large failed areas', 'Exterior expansion joints', 'Commercial food-service areas'] },
  assumptions: ['Joints are accessible and underlying tile remains secure unless identified otherwise.'], exclusions: ['Waterproofing replacement', 'Loose tile repair unless separately included', 'Structural movement repair', 'Mold remediation'],
  permitsAndCode: { permitMayBeRequired: false, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: false, notes: ['Selected materials must be suitable for the exposure and manufacturer requirements.'] }, researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
