import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const tileRepair = {
  identity: { id: 'tile-repair', slug: 'tile-repair', version: '1.0.0', name: 'Tile Repair', shortName: 'Tile Repair', description: 'Localized replacement or resetting of existing tile; full-room installation is excluded.', category: 'Tile', trade: 'tile', tags: ['tile', 'localized repair', 'grout'] },
  availability: { residential: true, commercial: true, emergencyEligible: false, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 2, typical: 5, maximum: 12 }, quantityUnit: 'item', setupHours: 0.75, cleanupHours: 0.75, productionRate: { quantity: 1.5, unit: 'tile', laborHours: 1, unitsPerTechnicianHour: { minimum: 0.5, typical: 1.5, maximum: 3 } }, returnVisits: { minimum: 1, typical: 2, maximum: 3 }, minimumBillableHoursOverride: 2 },
  materials: { costRange: { minimum: 25, typical: 100, maximum: 400 }, costUnit: 'typicalProject', typicalMaterials: ['Matching replacement tile', 'Thin-set mortar or approved adhesive', 'Grout', 'Sealant or movement-joint caulk', 'Spacers', 'Backer repair materials where minor', 'Protection materials', 'Cutting consumables', 'Cleaning supplies'], wasteFactorPercentage: 15, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: { typicalEquipment: ['Project-specific tile cutting or dust-control equipment when required'], rentalMayBeRequired: true, rentalCostRange: { minimum: 0, typical: 75, maximum: 350 }, elevatedAccessPossible: true, specialtyEquipmentNotes: ['Ordinary hand tools are not customer equipment charges.'] },
  timeline: { onsiteLaborHours: { minimum: 2, typical: 5, maximum: 12 }, calendarDurationDays: { minimum: 1, typical: 2, maximum: 4 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, dryingOrCuringTimeHours: { minimum: 2, typical: 12, maximum: 24 }, returnVisitRequired: true, weatherSensitive: false, permitMayAffectTimeline: false },
  pricing: { ...STANDARD_PRICING, minimumLaborHoursOverride: 2, wasteFactorPercentage: 15 },
  estimatorQuestions: [question('tileCount', 'Number of damaged tiles', 'number', ['labor', 'materials'], true), question('tileDimensions', 'Tile dimensions', 'measurement', ['labor', 'confidence'], true), question('floorOrWall', 'Floor or wall', 'singleSelect', ['labor', 'scope']), question('interiorOrExterior', 'Interior or exterior', 'singleSelect', ['timeline', 'manualReview']), question('matchingTileAvailable', 'Matching replacement tile available', 'boolean', ['confidence', 'recommendations']), question('tileMaterial', 'Tile material', 'singleSelect', ['labor', 'materials']), question('substrateType', 'Substrate type', 'text', ['scope', 'manualReview']), question('damageCondition', 'Tile loose, cracked, hollow, or missing', 'singleSelect', ['scope']), question('groutCondition', 'Grout condition', 'text', ['scope']), question('wetArea', 'Water exposure', 'boolean', ['labor', 'manualReview']), question('activeMoisture', 'Active moisture', 'boolean', ['manualReview']), question('adjacentTileCondition', 'Adjacent tile condition', 'text', ['manualReview']), question('accessDifficulty', 'Access', 'singleSelect', ['labor']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, { id: 'tile-large-format', name: 'Large-format tile', description: 'Large-format tile handling adjustment.', conditions: [{ field: 'largeFormatTile', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Large-format tile requires additional handling and fitting.', internalNotes: [] }, { id: 'tile-natural-stone', name: 'Natural stone', description: 'Natural-stone handling and material review.', conditions: [{ field: 'tileMaterial', operator: 'equals', value: 'natural-stone' }], effects: { laborMultiplier: 1.3, requiresManualReview: true }, customerExplanation: 'Natural stone requires material and finish-matching review.', internalNotes: [] }, { id: 'tile-wall', name: 'Wall tile', description: 'Wall tile labor adjustment.', conditions: [{ field: 'floorOrWall', operator: 'equals', value: 'wall' }], effects: { laborMultiplier: 1.1 }, customerExplanation: 'Wall tile requires additional positioning and support.', internalNotes: [] }, { id: 'tile-wet-area', name: 'Shower or wet area', description: 'Wet-area repair and waterproofing review.', conditions: [{ field: 'wetArea', operator: 'equals', value: true }], effects: { laborMultiplier: 1.25, requiresManualReview: true }, customerExplanation: 'Wet-area tile requires waterproofing review.', internalNotes: [] }, { id: 'tile-no-match', name: 'No matching tile available', description: 'Missing matching material reduces confidence.', conditions: [{ field: 'matchingTileAvailable', operator: 'equals', value: false }], effects: { confidenceAdjustment: -10, recommendationsToAdd: ['Provide customer-supplied matching tile or review a broader replacement area.'] }, customerExplanation: 'A matching replacement tile is needed for a localized repair.', internalNotes: [] }, { id: 'tile-substrate-repair', name: 'Tile substrate repair', description: 'Substrate repair allowance.', conditions: [{ field: 'substrateRepairRequired', operator: 'equals', value: true }], effects: { flatLaborHoursRange: { minimum: 2, typical: 5, maximum: 10 }, requiresManualReview: true, scopeStepsToAdd: ['Complete reviewed included minor substrate preparation.'] }, customerExplanation: 'Substrate damage may require additional preparation.', internalNotes: [] }, { id: 'tile-active-moisture', name: 'Active tile-area moisture', description: 'Active moisture requires direct review.', conditions: [{ field: 'activeMoisture', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Active moisture must be evaluated before tile repair.', internalNotes: [] }, { id: 'tile-over-20', name: 'More than 20 tiles', description: 'Larger tile scope requires review.', conditions: [{ field: 'tileCount', operator: 'greaterThan', value: 20 }], effects: { requiresManualReview: true }, customerExplanation: 'More than twenty tiles requires broader scope review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Tile count and dimensions', 'Matching tile', 'Substrate details', 'Photos'], reducesConfidence: ['No matching tile', 'Unknown substrate', 'Active moisture'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Protect the surrounding area.', 'Remove included damaged tile carefully.', 'Remove loose adhesive or mortar.', 'Inspect the visible substrate.', 'Complete included minor substrate preparation.', 'Cut and fit replacement tile.', 'Set tile using suitable bonding material.', 'Allow required curing time.', 'Grout repaired joints where included.', 'Apply suitable sealant where included.'], conditionalSteps: ['Evaluate visible moisture, adjacent tile, and substrate conditions without confirming concealed waterproofing.'], cleanupSteps: ['Clean the tile surface.', 'Remove included debris.'] },
  recommendations: { relatedServices: ['Grout and Caulk Repair'], customerPreparation: ['Provide matching replacement tile when available.'], professionalReviewTriggers: ['Active leak', 'Shower waterproofing failure', 'Loose surrounding tile', 'Structural movement', 'Cracked slab', 'Extensive substrate damage', 'Tile over 24 inches', 'Natural stone matching', 'Exterior freeze-thaw exposure', 'Commercial kitchen', 'Hazardous adhesive possibility', 'More than 20 tiles'] },
  assumptions: ['Repair is localized and matching tile is available or supplied.', 'Visible substrate requires only minor included preparation.'], exclusions: ['Full-room tile installation', 'Waterproofing-system replacement', 'Structural substrate repair', 'Hazardous-material abatement'],
  permitsAndCode: { permitMayBeRequired: false, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: false, notes: ['Wet-area waterproofing and structural conditions require separate review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
