import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, STANDARD_PRICING, question } from '../profileShared'
import { HVAC_EQUIPMENT, HVAC_MANUAL_REVIEW_MODIFIERS, HVAC_PERMIT_REVIEW, HVAC_SAFETY_OVERRIDE_MODIFIERS } from './hvacShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const hvacDiagnosticMinorRepair = {
  identity: { id: 'hvac-diagnostic-minor-repair', slug: 'hvac-diagnostic-minor-repair', version: '1.0.0', name: 'HVAC Diagnostic or Minor Repair', shortName: 'HVAC Diagnostics', description: 'Preliminary operational diagnostics and accessible minor service for conventional residential or light-commercial HVAC equipment.', category: 'HVAC', trade: 'hvac', tags: ['hvac', 'diagnostics', 'minor repair'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true }, crew: { defaultSize: 1, minimumSize: 1, maximumRecommendedSize: 2, secondTechnicianRequired: false, secondTechnicianReason: null },
  labor: { baseHours: { minimum: 1, typical: 2, maximum: 4 }, quantityUnit: 'system', setupHours: 0.25, cleanupHours: 0.5, returnVisits: { minimum: 1, typical: 1, maximum: 3 }, minimumBillableHoursOverride: 1 },
  materials: { costRange: { minimum: 0, typical: 20, maximum: 100 }, costUnit: 'typicalProject', costComponents: [{ name: 'Diagnostic visit consumables', costRange: { minimum: 0, typical: 20, maximum: 100 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false, conditions: [{ field: 'minorRepairIncluded', operator: 'notEquals', value: true }] }, { name: 'Accessible minor repair materials', costRange: { minimum: 10, typical: 125, maximum: 500 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false, conditions: [{ field: 'minorRepairIncluded', operator: 'equals', value: true }] }], typicalMaterials: ['Air filter', 'Accessible condensate components', 'Low-voltage fuse', 'Approved wire connectors', 'Accessible thermostat components', 'Minor control component when approved', 'Drain-line materials', 'Cleaning consumables', 'Minor available equipment panels or fasteners', 'Protection materials'], wasteFactorPercentage: 0, customerSuppliedAllowed: false, materialPickupUsuallyRequired: false, specialOrderPossible: true }, equipment: HVAC_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 4, maximum: 10 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 5, maximum: 14 }, returnVisitRequired: false, weatherSensitive: true, permitMayAffectTimeline: true }, pricing: STANDARD_PRICING,
  estimatorQuestions: [question('propertyType', 'Residential or commercial', 'singleSelect', ['labor']), question('equipmentType', 'Furnace, air conditioner, heat pump, package unit, mini-split, boiler, or unknown', 'singleSelect', ['manualReview'], true), question('manufacturer', 'Manufacturer', 'text', ['confidence']), question('modelNumber', 'Model number', 'text', ['confidence']), question('approximateAge', 'Approximate age', 'number', ['confidence']), question('issueType', 'Heating, cooling, both, or airflow issue', 'singleSelect', ['scope'], true), question('intermittentIssue', 'System completely inoperative or intermittent', 'boolean', ['labor', 'confidence']), question('thermostatDisplayActive', 'Thermostat display active', 'boolean', ['confidence']), question('filterCondition', 'Filter condition', 'text', ['confidence']), question('unusualNoise', 'Unusual noise', 'boolean', ['confidence']), question('unusualOdor', 'Unusual odor', 'boolean', ['manualReview']), question('waterLeakage', 'Water leakage', 'boolean', ['manualReview']), question('iceVisible', 'Ice visible', 'boolean', ['manualReview']), question('errorCode', 'Error code', 'text', ['confidence']), question('gasOdor', 'Gas odor', 'boolean', ['manualReview']), question('burningOdor', 'Burning smell', 'boolean', ['manualReview']), question('carbonMonoxideAlarm', 'Carbon-monoxide alarm', 'boolean', ['manualReview']), question('vulnerableOccupants', 'Vulnerable occupants', 'boolean', ['manualReview']), question('weatherConditions', 'Weather conditions', 'text', ['manualReview']), question('photos', 'Photos', 'photo', ['confidence'])],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, ...HVAC_MANUAL_REVIEW_MODIFIERS, ...HVAC_SAFETY_OVERRIDE_MODIFIERS,
    { id: 'hvac-minor-repair', name: 'Accessible minor repair included', description: 'Residential diagnostic with minor repair labor mode.', conditions: [{ field: 'minorRepairIncluded', operator: 'equals', value: true }], effects: { laborHoursOverride: { minimum: 2, typical: 4, maximum: 8 } }, customerExplanation: 'The range includes an accessible approved minor repair.', internalNotes: [] },
    { id: 'hvac-commercial-diagnostic', name: 'Light-commercial diagnostic', description: 'Light-commercial diagnostic labor mode.', conditions: [{ field: 'propertyContext', operator: 'equals', value: 'commercial' }], effects: { laborHoursOverride: { minimum: 2, typical: 4, maximum: 10 } }, customerExplanation: 'Light-commercial equipment uses the approved diagnostic labor range.', internalNotes: [] },
    { id: 'hvac-intermittent', name: 'Intermittent issue', description: 'Intermittent issue adjustment.', conditions: [{ field: 'intermittentIssue', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2, confidenceAdjustment: -10 }, customerExplanation: 'Intermittent symptoms may require additional observation and reduce preliminary confidence.', internalNotes: [] },
    { id: 'hvac-difficult-attic', name: 'Difficult attic or crawlspace access', description: 'Restricted access adjustment.', conditions: [{ field: 'difficultAtticOrCrawlspace', operator: 'equals', value: true }], effects: { laborMultiplier: 1.3 }, customerExplanation: 'Restricted equipment access requires additional work time.', internalNotes: [] },
    { id: 'hvac-rooftop-access', name: 'Rooftop access', description: 'Rooftop access requires equipment and safety review.', conditions: [{ field: 'rooftopAccess', operator: 'equals', value: true }], effects: { laborMultiplier: 1.3, requiresManualReview: true, manualReviewFlags: ['licensingReviewRequired'], recommendationsToAdd: ['Confirm rooftop access equipment and safety requirements.'] }, customerExplanation: 'Rooftop equipment requires direct access and safety review.', internalNotes: [] },
    { id: 'hvac-commercial-occupied', name: 'Commercial occupied facility', description: 'Occupied commercial access adjustment.', conditions: [{ field: 'propertyContext', operator: 'equals', value: 'commercial' }, { field: 'occupied', operator: 'equals', value: true }], effects: { laborMultiplier: 1.1 }, customerExplanation: 'Occupied commercial work may require access coordination.', internalNotes: [] },
    { id: 'hvac-additional-systems', name: 'Additional systems', description: 'Additional-system diagnostic allowance.', conditions: [{ field: 'additionalSystemCount', operator: 'greaterThan', value: 0 }], effects: { laborHoursPerUnit: { minimum: 1, typical: 2, maximum: 4 }, laborUnitField: 'additionalSystemCount' }, customerExplanation: 'Each additional system requires separate observation and testing.', internalNotes: [] },
    { id: 'hvac-no-model', name: 'No equipment model information', description: 'Missing model information reduces confidence.', conditions: [{ field: 'modelNumber', operator: 'equals', value: '' }], effects: { confidenceAdjustment: -5 }, customerExplanation: 'Equipment model information improves planning confidence.', internalNotes: [] },
    { id: 'hvac-ice', name: 'Visible ice buildup', description: 'Visible ice requires sealed-system review.', conditions: [{ field: 'iceVisible', operator: 'equals', value: true }], effects: { requiresManualReview: true, manualReviewFlags: ['refrigerantCertificationRequired'] }, customerExplanation: 'Visible ice can have multiple causes and requires qualified review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Equipment type, manufacturer, model, and age', 'Detailed operating symptoms and error codes', 'Photos of visible conditions', 'Recent service information'], reducesConfidence: ['Intermittent symptoms', 'Missing equipment model', 'No photos where symptoms are visible', 'Unknown equipment type'], requiredForStrongConfidence: ['equipmentType', 'issueType', 'modelNumber', 'photos'] },
  scopeOfWork: { standardSteps: ['Review reported system symptoms and accessible equipment information.', 'Inspect accessible thermostat and filter conditions.', 'Observe the available operating sequence.', 'Inspect accessible visible electrical and condensate conditions.', 'Perform applicable non-invasive diagnostic checks.', 'Complete included accessible minor maintenance or an approved minor repair.', 'Restore panels and controls and test available normal operation.', 'Document unresolved conditions and recommend specialized review where required.'], conditionalSteps: [], cleanupSteps: ['Clean the work area.'] },
  recommendations: { relatedServices: ['Thermostat Replacement'], customerPreparation: ['Provide equipment type, manufacturer, model, age, symptoms, error codes, weather conditions, and photos.'], professionalReviewTriggers: ['Sealed-system or refrigerant-circuit work', 'Compressor, coil, or heat-exchanger concern', 'Gas, combustion, venting, or carbon-monoxide concern', 'Boiler, hydronic, geothermal, rooftop, building-automation, or industrial equipment', 'Electrical service issue', 'Major equipment replacement or duct redesign', 'Hazardous-weather no-heat condition or vulnerable occupants', 'Permit or licensing uncertainty'] },
  assumptions: ['Safe equipment access and utilities are available for testing.', 'No sealed-system access, gas-pressure adjustment, combustion adjustment, or major component replacement is included.'], exclusions: ['Sealed-system handling, charging, recovery, leak repair, compressor, or coil work', 'Heat-exchanger or major gas work', 'Major equipment replacement', 'Duct-system redesign', 'Building automation', 'Permit fees', 'Specialty part costs unless included after diagnosis'], permitsAndCode: HVAC_PERMIT_REVIEW, researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
