import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, OCCUPIED_PROTECTION_MODIFIER, STANDARD_PRICING, question } from '../profileShared'
import { HVAC_EQUIPMENT, HVAC_MANUAL_REVIEW_MODIFIERS, HVAC_PERMIT_REVIEW, HVAC_SAFETY_OVERRIDE_MODIFIERS } from './hvacShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const thermostatReplacement = {
  identity: { id: 'thermostat-replacement', slug: 'thermostat-replacement', version: '1.0.0', name: 'Thermostat Replacement', shortName: 'Thermostat', description: 'Replacement of an existing compatible low-voltage thermostat in the same location using serviceable existing thermostat wiring.', category: 'HVAC', trade: 'hvac', tags: ['thermostat', 'controls', 'hvac'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true }, crew: { defaultSize: 1, minimumSize: 1, maximumRecommendedSize: 2, secondTechnicianRequired: false, secondTechnicianReason: null },
  labor: { baseHours: { minimum: 1, typical: 1.5, maximum: 3 }, quantityUnit: 'thermostat', setupHours: 0.25, cleanupHours: 0.25, returnVisits: { minimum: 1, typical: 1, maximum: 2 }, minimumBillableHoursOverride: 1 },
  materials: { costRange: { minimum: 5, typical: 30, maximum: 150 }, costUnit: 'typicalProject', costComponents: [{ name: 'Connection, mounting, and accessory materials', costRange: { minimum: 5, typical: 30, maximum: 150 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false }, { name: 'Contractor-supplied thermostat allowance', costRange: { minimum: 30, typical: 150, maximum: 450 }, costUnit: 'perItem', customerSuppliedEligible: true, applyWasteFactor: false }], typicalMaterials: ['Replacement thermostat', 'Thermostat wall plate', 'Low-voltage connectors', 'Mounting fasteners', 'Wall anchors', 'Wire labels', 'Minor wall-finish cover plate', 'Common-wire accessory when compatible and specifically included', 'Protection materials'], wasteFactorPercentage: 0, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true }, equipment: HVAC_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 3, maximum: 8 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 2 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 3, maximum: 21 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: true }, pricing: STANDARD_PRICING,
  estimatorQuestions: [question('propertyType', 'Residential or commercial', 'singleSelect', ['labor']), question('existingThermostatModel', 'Existing thermostat manufacturer and model', 'text', ['confidence']), question('replacementThermostatModel', 'Replacement thermostat manufacturer and model', 'text', ['confidence'], true), question('systemType', 'Conventional furnace, heat pump, boiler, or other', 'singleSelect', ['labor', 'manualReview'], true), question('auxiliaryHeat', 'Auxiliary or emergency heat', 'boolean', ['manualReview']), question('multiStageEquipment', 'Multi-stage equipment', 'boolean', ['labor']), question('zonedSystem', 'Zoned system', 'boolean', ['manualReview']), question('communicatingSystem', 'Communicating system', 'boolean', ['manualReview']), question('lineVoltage', 'Line-voltage thermostat', 'boolean', ['manualReview']), question('thermostatWireCount', 'Number of thermostat wires', 'number', ['confidence']), question('commonWirePresent', 'Common wire present', 'boolean', ['manualReview']), question('existingWiringPhoto', 'Existing wiring photo', 'photo', ['confidence'], true), question('equipmentModelNumbers', 'Equipment model numbers', 'text', ['confidence']), question('wifiAvailable', 'Wi-Fi available', 'boolean', ['scope']), question('smartThermostat', 'Smart thermostat', 'boolean', ['labor']), question('currentSystemOperational', 'Current system operational', 'boolean', ['manualReview']), question('customerSuppliedMaterials', 'Customer supplying thermostat', 'boolean', ['materials']), question('photos', 'Photos', 'photo', ['confidence'])],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, OCCUPIED_PROTECTION_MODIFIER, ...HVAC_MANUAL_REVIEW_MODIFIERS, ...HVAC_SAFETY_OVERRIDE_MODIFIERS,
    { id: 'thermostat-smart', name: 'Smart thermostat', description: 'Smart thermostat labor adjustment.', conditions: [{ field: 'smartThermostat', operator: 'equals', value: true }], effects: { flatLaborHoursRange: { minimum: 0.5, typical: 1, maximum: 2 } }, customerExplanation: 'Smart thermostat setup requires additional compatibility and configuration time.', internalNotes: [] },
    { id: 'thermostat-heat-pump', name: 'Heat-pump thermostat', description: 'Heat-pump labor mode.', conditions: [{ field: 'systemType', operator: 'equals', value: 'heat-pump' }], effects: { laborHoursOverride: { minimum: 2, typical: 3.5, maximum: 6 }, recommendationsToAdd: ['Confirm heat-pump staging and auxiliary-heat compatibility.'] }, customerExplanation: 'Heat-pump controls require additional configuration review.', internalNotes: [] },
    { id: 'thermostat-commercial', name: 'Commercial low-voltage thermostat', description: 'Commercial thermostat labor mode.', conditions: [{ field: 'propertyContext', operator: 'equals', value: 'commercial' }], effects: { laborHoursOverride: { minimum: 2, typical: 4, maximum: 8 } }, customerExplanation: 'Commercial controls require additional access and system review.', internalNotes: [] },
    { id: 'thermostat-multistage', name: 'Multi-stage equipment', description: 'Multi-stage control adjustment.', conditions: [{ field: 'multiStageEquipment', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Multi-stage equipment requires additional configuration review.', internalNotes: [] },
    { id: 'thermostat-no-common', name: 'No common wire', description: 'Compatibility requires direct review.', conditions: [{ field: 'commonWirePresent', operator: 'equals', value: false }], effects: { requiresManualReview: true, recommendationsToAdd: ['Confirm whether a compatible accessory or new control wire is required.'] }, customerExplanation: 'A missing common wire requires compatibility review.', internalNotes: [] },
    { id: 'thermostat-line-voltage', name: 'Line-voltage thermostat', description: 'Line-voltage work is excluded from ordinary replacement pricing.', conditions: [{ field: 'lineVoltage', operator: 'equals', value: true }], effects: { requiresManualReview: true, manualReviewFlags: ['electricalProfessionalReviewRequired', 'licensingReviewRequired'] }, customerExplanation: 'Line-voltage controls require qualified professional review.', internalNotes: [] },
    { id: 'thermostat-wall-finish', name: 'Wall repair or paint mismatch', description: 'Wall finish is a related scope.', conditions: [{ field: 'wallRepairNeeded', operator: 'equals', value: true }], effects: { recommendationsToAdd: ['Review related minor wall repair or paint matching separately.'] }, customerExplanation: 'Wall finish work is not silently included.', internalNotes: [] },
    { id: 'thermostat-inoperative', name: 'System not operating before replacement', description: 'Pre-existing system failure requires diagnosis.', conditions: [{ field: 'currentSystemOperational', operator: 'equals', value: false }], effects: { requiresManualReview: true, recommendationsToAdd: ['Review HVAC Diagnostic or Minor Repair before assuming thermostat replacement will restore operation.'] }, customerExplanation: 'A pre-existing system issue requires diagnostic review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Existing and replacement thermostat models', 'Equipment type and model numbers', 'Wire count and common-wire status', 'Clear wiring photos'], reducesConfidence: ['Unknown wiring or system staging', 'Inoperative equipment', 'Proprietary or zoned controls'], requiredForStrongConfidence: ['replacementThermostatModel', 'systemType', 'existingWiringPhoto'] },
  scopeOfWork: { standardSteps: ['Confirm thermostat and equipment information.', 'Protect the work area.', 'Have a qualified person safely isolate applicable system controls.', 'Document accessible existing thermostat connections.', 'Remove the existing thermostat and inspect visible thermostat wiring.', 'Install a compatible replacement thermostat and complete included basic configuration.', 'Restore system controls and test available heating and cooling calls where conditions permit.', 'Explain basic included operation and document unresolved concerns.'], conditionalSteps: [], cleanupSteps: ['Clean the work area.'] },
  recommendations: { relatedServices: ['HVAC Diagnostic or Minor Repair'], customerPreparation: ['Provide thermostat and equipment models, clear wiring photos, Wi-Fi credentials, and required account access.'], professionalReviewTriggers: ['Line-voltage or proprietary communicating thermostat', 'Building automation, zoning, boiler, or hydronic controls', 'More than two stages', 'Unknown or damaged wiring', 'New control wire', 'Equipment failure, control-board, or transformer concern', 'Commercial rooftop controls', 'Permit or licensing uncertainty'] },
  assumptions: ['Existing thermostat wiring is serviceable and the replacement thermostat is compatible.', 'HVAC equipment is otherwise operational and no new control wire is required.', 'Required Wi-Fi credentials and smart-device account access are available when applicable.'], exclusions: ['Major HVAC diagnosis or equipment repair', 'New thermostat wiring', 'Line-voltage controls', 'Control-board or zoning modification', 'Building automation', 'Refrigerant or gas-system work', 'Permit fees', 'Subscriptions or extended smart-home configuration'], permitsAndCode: HVAC_PERMIT_REVIEW, researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
