import type { ResourceSection } from '../../components/Resources/ResourcePageLayout'
export type Article = { category: string; title: string; intro: string; sections: ResourceSection[]; tip?: string; warning?: string }
const make = (category:string,title:string,intro:string,sections:ResourceSection[],tip?:string,warning?:string):Article=>({category,title,intro,sections,tip,warning})
export const homeMaintenance=make('Resource Library','Home Maintenance Resources','A practical reference for planning routine upkeep, noticing early warning signs, and preparing your home for seasonal changes.',[
{heading:'Routine Home Maintenance',copy:'A consistent maintenance schedule helps protect finishes, equipment, and the systems that support daily life.',items:['Create monthly, seasonal, and annual task lists','Plan preventative repairs before small defects spread','Keep notes on recurring concerns and completed work']},
{heading:'Interior Checks',copy:'Walk through living spaces regularly and document changes before they become disruptive.',items:['Check plumbing fixtures and visible leaks','Replace HVAC filters and test thermostat operation','Inspect doors, locks, windows, flooring, drywall, and tile','Test appliances and safety devices','Annually inspect the water heater expansion tank and verify the internal bladder is properly pressurized and functioning','Drain and flush the hot water heater at least once per year to remove sediment buildup and improve efficiency','If your home has a sump pump, pour water into the sump pit to verify the pump activates properly and discharges water correctly','Inspect the caulking around exterior doors and windows. Replace cracked, missing, or deteriorated caulk to prevent air and water infiltration','Clean the HVAC thermopile (flame sensor) at least once per heating season to help maintain reliable furnace ignition and operation']},
{heading:'Exterior Planning',copy:'Weather and drainage have an outsized effect on a home’s condition.',items:['Review siding, trim, and exterior openings','Keep drainage paths and irrigation areas clear','Watch for pooling water, damaged seals, or loose materials']}], 'Take photos of new stains, cracks, or water marks so you can track changes over time.')
export const commercialFacilities=make('Resource Library','Commercial Facility Resources','Use this guide to organize preventative maintenance and help facility teams identify conditions that need timely attention.',[
{heading:'Facility Inspection Basics',copy:'Regular observations create a useful baseline for busy commercial properties.',items:['Review interior and exterior conditions','Check lighting, electrical fixtures, and visible wiring concerns','Inspect plumbing fixtures and shutoff valves','Watch ceiling tiles for stains or water damage']},
{heading:'Access, HVAC & Exterior',copy:'Prioritize systems that affect safety, access, comfort, and customer experience.',items:['Check doors, locks, hardware, and access points','Review HVAC filters and thermostat operation','Inspect parking lot conditions and striping','Note exterior signage and storefront conditions']},
{heading:'Documentation & Emergency Planning',copy:'A consistent record helps teams make faster, better repair decisions.',items:['Maintain dated maintenance documentation','Record issue locations and photographs','Keep an emergency repair contact plan current']}])
export const propertyManagement=make('Resource Library','Property Management Resources','A concise framework for turnovers, inspections, and recurring maintenance across managed properties.',[
{heading:'Turnovers & Make-Ready Planning',copy:'A clear turnover process helps reduce vacancy time and missed repairs.',items:['Complete an initial condition inspection','Plan lock changes and access control','Test appliances before the next occupancy','Coordinate cleaning and make-ready tasks']},
{heading:'Property Condition Checks',copy:'Review core systems and finishes consistently between residents.',items:['Inspect plumbing and visible leaks','Document drywall, flooring, and trim repairs','Test smoke, carbon monoxide, and other safety devices','Keep detailed maintenance documentation']},
{heading:'Portfolio Coordination',copy:'Organized scheduling supports better service across multiple properties.',items:['Coordinate vendor access and scope details','Track open repair items by priority','Build preventative maintenance schedules']}])
export const propertyInspections=make('Resource Library','Property Inspection Resources','Inspection notes and photographs help turn observations into a clear, prioritized repair plan.',[
{heading:'Interior & System Review',copy:'Look for changes in finishes and visible building systems.',items:['Review flooring, drywall, tile, doors, locks, and windows','Check plumbing fixtures and accessible connections','Observe HVAC operation and electrical concerns','Note odors, unusual sounds, or reduced performance']},
{heading:'Exterior & Water Warning Signs',copy:'Exterior conditions often reveal drainage and weather-related issues.',items:['Inspect siding, trim, roofline, and drainage','Look for ceiling or wall discoloration','Document signs of water damage with photographs','Review irrigation and exterior openings']},
{heading:'Prioritizing Findings',copy:'Not every issue has the same urgency or impact.',items:['Separate immediate safety concerns from routine repairs','Use repair priority rankings','Request a professional assessment for complex or recurring conditions']}])
export const repairPlanning=make('Resource Library','Repair Planning Resources','Use a structured plan to prioritize repairs, prepare budgets, and make contractor visits more productive.',[
{heading:'Set Repair Priorities',copy:'Start with safety, active damage, and issues that can affect adjacent systems.',items:['Identify immediate safety concerns','Separate urgent and non-urgent repairs','Compare preventative versus corrective maintenance','Assign clear repair priority levels']},
{heading:'Prepare the Project',copy:'Good documentation improves scope conversations and scheduling.',items:['Document existing conditions with photos and notes','Plan materials and access requirements','Schedule related repairs together when practical','Prepare questions for contractor visits']},
{heading:'Budget & Scope',copy:'A realistic plan accounts for the work itself and potential findings.',items:['Estimate project costs with clear priorities','Reserve room for concealed-condition discoveries','Confirm what is included before work begins']}])
export const assessmentReports=make('Professional Assessments','Professional Property Assessment Reports','A professional assessment turns visible property conditions into clear documentation, repair recommendations, and a practical path forward.',[
{heading:'What an Assessment Includes',copy:'The report documents existing conditions in a format that is easy to review and share.',items:['Interior and exterior documentation','High-resolution photographs','Detailed inspection findings','Professional PDF report']},
{heading:'Recommendations & Priorities',copy:'Findings are organized to help owners plan the next steps.',items:['Repair recommendations','Maintenance priorities','Estimated repair costs','Clear condition documentation']},
{heading:'Who Benefits',copy:'Assessments support better decisions for many property types.',items:['Homeowners and property managers','Commercial property owners','Financial institutions and government agencies','A $49 flat-rate assessment option']}], 'An assessment is a practical planning document; it is not a substitute for a code-compliance inspection or specialized engineering evaluation.')
export const seasonalHome=make('Featured Guide','Seasonal Home Maintenance Guide','Seasonal attention helps homeowners spot changing conditions and plan practical upkeep throughout the year.',[
{heading:'Spring & Summer',copy:'Focus on drainage, weather exposure, and systems that work harder in warm weather.',items:['Check exterior drainage and irrigation','Inspect siding, trim, windows, and weather seals','Clear outdoor unit areas and test thermostat operation','Look for leaks after seasonal storms']},
{heading:'Fall & Winter',copy:'Prepare the home for colder temperatures and increased moisture exposure.',items:['Review plumbing freeze protection','Check roofline and visible exterior damage','Test smoke and carbon monoxide detectors','Inspect doors, locks, and weather seals']},
{heading:'Monthly & Annual Checks',copy:'Regular observations help identify changes before they grow.',items:['Replace filters as recommended','Test safety devices monthly','Schedule an annual professional system review','Document new stains, cracks, or unusual sounds']}])
export const commercialPreventative=make('Featured Guide','Commercial Preventative Maintenance Guide','A preventative program gives facility teams a repeatable way to observe conditions, plan maintenance, and maintain useful records.',[
{heading:'Daily & Monthly Observations',copy:'Frontline observations often identify issues before they affect operations.',items:['Note lighting, access, and visible water concerns','Inspect plumbing fixtures and high-use doors','Review interior building conditions','Maintain dated maintenance records']},
{heading:'Quarterly & Seasonal Maintenance',copy:'Plan recurring work around weather and equipment demands.',items:['Review HVAC filters and thermostats','Inspect exterior conditions and parking areas','Check electrical fixtures and interior finishes','Prepare plumbing and drainage for seasonal weather']},
{heading:'Annual Facility Review',copy:'A larger review helps align budgets and priorities.',items:['Review HVAC, plumbing, and electrical performance','Assess exterior conditions and signage','Update emergency planning documentation','Prioritize upcoming facility work']}])
export const rentalTurnover=make('Featured Guide','Rental Property Turnover Guide','A consistent turnover checklist helps property teams document condition, coordinate repairs, and prepare a unit for its next resident.',[
{heading:'Initial Review & Documentation',copy:'Start with a complete snapshot of the property condition.',items:['Complete an initial condition inspection','Take photographic documentation','Identify drywall, paint, and flooring repairs','Create a final make-ready checklist']},
{heading:'Systems & Access',copy:'Confirm core functions before turnover is complete.',items:['Complete lock changes','Test appliances','Inspect plumbing fixtures and leaks','Check electrical, lighting, and HVAC operation']},
{heading:'Final Readiness',copy:'Close out items that support safety and presentation.',items:['Test safety devices','Coordinate cleaning','Confirm access for vendors','Document completed work']}])
export const waterDamage=make('Featured Guide','Water Damage Prevention Guide','Water damage is easier to manage when leaks, drainage concerns, and visible warning signs are documented early.',[
{heading:'Common Sources & Checks',copy:'Review accessible water systems and areas where moisture commonly appears.',items:['Check plumbing fixtures and visible supply lines','Inspect water heater surroundings','Locate and exercise shutoff valves when safe','Review irrigation and exterior drainage']},
{heading:'Warning Signs',copy:'Changes in finishes can indicate moisture behind surfaces.',items:['Look for ceiling and wall discoloration','Watch for flooring damage or soft areas','Review roofline and exterior warning signs','Note musty odors or mold warning signs']},
{heading:'Emergency Response',copy:'Protect people and property while help is arranged.',items:['Document damage and take photographs','Shut off water only when safe to do so','Avoid opening walls or handling electrical hazards','Contact an appropriate professional for active or extensive damage']}])
export const hvacMaintenance=make('Featured Guide','HVAC Maintenance Guide','Routine observation and safe maintenance practices can support HVAC performance, comfort, and equipment life.',[
{heading:'Routine Checks',copy:'Focus on accessible items and clear signs of reduced performance.',items:['Replace filters as recommended','Check thermostat settings and operation','Inspect vents and registers for obstructions','Keep outdoor unit areas clear of debris']},
{heading:'Seasonal Preparation',copy:'Prepare early for the demands of heating and cooling seasons.',items:['Observe airflow and comfort changes','Note unusual sounds or odors','Watch for energy efficiency concerns','Schedule preventative professional maintenance']},
{heading:'Professional Service',copy:'HVAC systems involve components that require qualified service.',items:['Use EPA-certified service for refrigerant work','Do not open sealed systems','Do not work inside electrical panels','Contact a professional for persistent performance concerns']}], 'Avoid DIY repairs involving refrigerants, electrical panels, or sealed HVAC equipment.')
export const emergencyRepair=make('Featured Guide','Emergency Repair Preparation Guide','A calm, documented response can protect occupants and help the right professional understand the issue quickly.',[
{heading:'Protect People First',copy:'Your safety and the safety of occupants is always the first priority.',items:['Move away from the affected area when needed','Shut off water only when safe','Turn off affected equipment only when safe','Avoid unsafe DIY repairs']},
{heading:'Document & Prepare',copy:'Clear information helps repair teams respond efficiently.',items:['Take photographs of visible damage','Locate utility shutoffs','Gather property and insurance information','Prepare safe access for the repair technician']},
{heading:'Contact the Right Help',copy:'Different hazards require different emergency responses.',items:['Contact the appropriate professional','Notify property management when applicable','Keep notes on timing and visible changes']}],undefined,'For fire, gas leaks, electrical hazards, structural collapse or immediate danger, leave the area and contact emergency services or the appropriate utility provider.')
