import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'
import { PLUMBING_CLEANUP_SCOPE, PLUMBING_DIRECT_CONTACT_MODIFIERS, PLUMBING_EQUIPMENT, PLUMBING_PERMIT_REVIEW, PLUMBING_STANDARD_SCOPE } from './plumbingShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const hoseBibRepairReplacement = {
  identity: { id: 'hose-bib-repair-replacement', slug: 'hose-bib-repair-replacement', version: '1.0.0', name: 'Hose Bib Repair or Replacement', shortName: 'Hose Bib Service', description: 'Repair or replace an accessible standard hose bib or frost-free sillcock.', category: 'Plumbing', trade: 'plumbing', tags: ['hose bib', 'sillcock', 'exterior plumbing'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true }, crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 1, typical: 1.5, maximum: 3 }, quantityUnit: 'fixture', setupHours: 0.25, cleanupHours: 0.5, returnVisits: { minimum: 1, typical: 1, maximum: 2 } },
  materials: { costRange: { minimum: 10, typical: 50, maximum: 125 }, costUnit: 'typicalProject', costComponents: [{ name: 'Minor hose-bib repair materials', costRange: { minimum: 10, typical: 35, maximum: 75 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false, conditions: [{ field: 'repairOrReplacement', operator: 'equals', value: 'repair' }] }, { name: 'Hose-bib replacement materials', costRange: { minimum: 30, typical: 125, maximum: 400 }, costUnit: 'perItem', customerSuppliedEligible: true, applyWasteFactor: false, conditions: [{ field: 'repairOrReplacement', operator: 'equals', value: 'replacement' }] }], typicalMaterials: ['Hose bib or frost-free sillcock', 'Vacuum breaker', 'Stem or washer repair parts', 'PEX, copper, or approved pipe section', 'Fittings', 'Interior shutoff valve where included', 'Fasteners', 'Exterior sealant', 'Insulation where appropriate', 'Pipe supports', 'Protection materials'], wasteFactorPercentage: 0, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true }, equipment: PLUMBING_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 3, maximum: 12 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, returnVisitRequired: false, weatherSensitive: true, permitMayAffectTimeline: true }, pricing: STANDARD_PRICING,
  estimatorQuestions: [question('repairOrReplacement', 'Repair or replacement', 'singleSelect', ['labor', 'materials', 'scope'], true), question('leakLocation', 'Leak location', 'text', ['scope']), question('frostFree', 'Frost-free or standard', 'singleSelect', ['materials']), question('pipeMaterial', 'Pipe material', 'text', ['labor', 'materials']), question('interiorConnectionAccessible', 'Interior connection accessible', 'boolean', ['labor', 'manualReview'], true), question('interiorShutoffPresent', 'Interior shutoff present', 'boolean', ['manualReview']), question('wallThickness', 'Wall thickness', 'measurement', ['materials', 'confidence']), question('freezeDamage', 'Freeze damage', 'boolean', ['labor', 'manualReview']), question('exteriorWallFinish', 'Exterior wall finish', 'text', ['labor', 'manualReview']), question('shutoffFunctioning', 'Water can be shut off', 'boolean', ['manualReview'], true), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, ...PLUMBING_DIRECT_CONTACT_MODIFIERS, { id: 'hose-replacement', name: 'Accessible hose bib replacement', description: 'Replacement labor mode.', conditions: [{ field: 'repairOrReplacement', operator: 'equals', value: 'replacement' }], effects: { laborHoursOverride: { minimum: 1.5, typical: 3, maximum: 6 }, scopeStepsToAdd: ['Remove the existing hose bib and install the included replacement.'] }, customerExplanation: 'Accessible replacement uses the approved replacement labor range.', internalNotes: [] }, { id: 'hose-wall-access', name: 'Interior-wall access required', description: 'Interior-wall access labor mode.', conditions: [{ field: 'interiorConnectionAccessible', operator: 'equals', value: false }], effects: { laborHoursOverride: { minimum: 3, typical: 6, maximum: 12 }, requiresManualReview: true }, customerExplanation: 'Interior-wall access requires direct scope review.', internalNotes: [] }, { id: 'hose-copper', name: 'Copper hose-bib connection', description: 'Copper connection adjustment.', conditions: [{ field: 'pipeMaterial', operator: 'equals', value: 'copper' }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Copper connection work requires additional preparation.', internalNotes: [] }, { id: 'hose-freeze', name: 'Hose-bib freeze damage', description: 'Freeze damage adjustment and review.', conditions: [{ field: 'freezeDamage', operator: 'equals', value: true }], effects: { laborMultiplier: 1.3, requiresManualReview: true }, customerExplanation: 'Freeze damage may extend into concealed piping.', internalNotes: [] }, { id: 'hose-masonry', name: 'Masonry exterior', description: 'Masonry exterior adjustment.', conditions: [{ field: 'masonryExterior', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Masonry exterior access requires additional preparation.', internalNotes: [] }, { id: 'hose-no-shutoff', name: 'No upstream hose-bib shutoff', description: 'No functioning shutoff requires review.', conditions: [{ field: 'shutoffFunctioning', operator: 'equals', value: false }], effects: { requiresManualReview: true }, customerExplanation: 'A functioning water shutoff must be confirmed.', internalNotes: [] }, { id: 'hose-frost-free', name: 'New frost-free sillcock', description: 'Frost-free product requirements.', conditions: [{ field: 'frostFree', operator: 'equals', value: 'frost-free' }, { field: 'repairOrReplacement', operator: 'equals', value: 'replacement' }], effects: { recommendationsToAdd: ['Confirm the required sillcock length and drainage pitch.'] }, customerExplanation: 'Frost-free sillcock length and pitch must match the wall assembly.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Repair selection', 'Pipe and wall details', 'Interior access', 'Shutoff status', 'Photos'], reducesConfidence: ['Concealed freeze damage', 'Unknown connection', 'No functioning shutoff'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Confirm the reported leak or replacement condition.', ...PLUMBING_STANDARD_SCOPE, 'Complete the included repair or remove the existing hose bib.', 'Prepare the accessible pipe connection.', 'Install the selected replacement component.', 'Secure the fixture to the structure.', 'Seal the exterior penetration where included.'], conditionalSteps: ['Confirm frost-free sillcock length and pitch.', 'Document visible additional freeze damage.'], cleanupSteps: PLUMBING_CLEANUP_SCOPE },
  recommendations: { relatedServices: ['Shutoff Valve Replacement', 'Drywall Repair'], customerPreparation: ['Confirm interior connection access and shutoff location.'], professionalReviewTriggers: ['Active flooding', 'Concealed freeze damage', 'No functioning shutoff', 'Brick, stone, stucco, or specialty cladding requiring substantial alteration', 'Severely deteriorated pipe', 'Multiple frozen sections', 'Commercial shutdown', 'Fire-suppression connection', 'Permit uncertainty'] },
  assumptions: ['Accessible piping and shutoff function are not assumed until verified.', 'Exterior penetration requires only included minor sealing.'], exclusions: ['Concealed freeze-damage repair', 'Substantial cladding alteration', 'Fire-suppression connections', 'Interior wall finish repair unless separately included'], permitsAndCode: PLUMBING_PERMIT_REVIEW, researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
