import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'
import { PLUMBING_CLEANUP_SCOPE, PLUMBING_DIRECT_CONTACT_MODIFIERS, PLUMBING_EQUIPMENT, PLUMBING_PERMIT_REVIEW, PLUMBING_STANDARD_SCOPE } from './plumbingShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const minorPlumbingLeakRepair = {
  identity: { id: 'minor-plumbing-leak-repair', slug: 'minor-plumbing-leak-repair', version: '1.0.0', name: 'Minor Plumbing Leak Repair', shortName: 'Minor Leak Repair', description: 'Repair a visible, accessible, localized supply or drain leak with a reasonably identified source.', category: 'Plumbing', trade: 'plumbing', tags: ['leak repair', 'accessible plumbing', 'supply or drain'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true }, crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 1, typical: 3, maximum: 8 }, quantityUnit: 'project', setupHours: 0.25, cleanupHours: 0.5, returnVisits: { minimum: 1, typical: 1, maximum: 2 } },
  materials: { costRange: { minimum: 10, typical: 100, maximum: 400 }, costUnit: 'typicalProject', typicalMaterials: ['Pipe section', 'Fittings', 'Couplings', 'Supply connectors', 'Drain components', 'Clamps or supports', 'Thread-sealing materials', 'Protection and cleanup materials'], wasteFactorPercentage: 5, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true }, equipment: PLUMBING_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 3, maximum: 8 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: true }, pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 5 },
  estimatorQuestions: [question('leakSystem', 'Supply or drain', 'singleSelect', ['labor', 'scope'], true), question('activeOrIntermittent', 'Active or intermittent', 'singleSelect', ['manualReview']), question('sourceKnown', 'Exact visible source known', 'boolean', ['confidence', 'manualReview'], true), question('pipeMaterial', 'Pipe material', 'text', ['labor', 'materials']), question('pipeSize', 'Pipe size', 'measurement', ['materials']), question('accessible', 'Accessible location', 'boolean', ['manualReview'], true), question('shutoffFunctioning', 'Water can be shut off', 'boolean', ['manualReview'], true), question('surfaceDamage', 'Damage to surrounding surfaces', 'boolean', ['recommendations']), question('leakDuration', 'Duration of leak', 'text', ['confidence']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, ...PLUMBING_DIRECT_CONTACT_MODIFIERS, { id: 'leak-copper', name: 'Copper leak repair', description: 'Copper repair adjustment.', conditions: [{ field: 'pipeMaterial', operator: 'equals', value: 'copper' }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Copper repair requires additional preparation.', internalNotes: [] }, { id: 'leak-aged-pipe', name: 'Brittle or aged piping', description: 'Aged piping adjustment and review.', conditions: [{ field: 'agedPiping', operator: 'equals', value: true }], effects: { laborMultiplier: 1.3, requiresManualReview: true }, customerExplanation: 'Brittle or aged piping may fail beyond the visible repair.', internalNotes: [] }, { id: 'leak-drain', name: 'Drain leak', description: 'Drain leak adjustment.', conditions: [{ field: 'leakSystem', operator: 'equals', value: 'drain' }], effects: { laborMultiplier: 1.1 }, customerExplanation: 'Drain components may require additional access and fitting.', internalNotes: [] }, { id: 'leak-ceiling', name: 'Ceiling access', description: 'Ceiling access adjustment.', conditions: [{ field: 'ceilingOrElevatedWork', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Ceiling access requires additional protection and positioning.', internalNotes: [] }, { id: 'leak-drywall-opening', name: 'Drywall opening required', description: 'Drywall access allowance.', conditions: [{ field: 'drywallOpeningRequired', operator: 'equals', value: true }], effects: { flatLaborHoursRange: { minimum: 1, typical: 2, maximum: 3 }, recommendationsToAdd: ['Review Drywall Repair as a related service.'], scopeStepsToAdd: ['Create included limited access opening where reviewed.'] }, customerExplanation: 'A limited access opening may be required; finish repair is separate.', internalNotes: [] }, { id: 'leak-source-unknown', name: 'Unknown leak source', description: 'Unknown source is outside this profile.', conditions: [{ field: 'sourceKnown', operator: 'equals', value: false }], effects: { requiresManualReview: true, confidenceAdjustment: -15 }, customerExplanation: 'The leak source must be reasonably identified for this profile.', internalNotes: [] }, { id: 'leak-concealed', name: 'Concealed plumbing leak', description: 'Concealed leak requires direct review.', conditions: [{ field: 'accessible', operator: 'equals', value: false }], effects: { requiresManualReview: true }, customerExplanation: 'Concealed leaks require direct diagnostic review.', internalNotes: [] }, { id: 'leak-no-shutoff', name: 'No functioning leak shutoff', description: 'No working shutoff requires review.', conditions: [{ field: 'shutoffFunctioning', operator: 'equals', value: false }], effects: { requiresManualReview: true }, customerExplanation: 'A functioning shutoff must be confirmed.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Visible known source', 'Pipe material and size', 'Shutoff status', 'Photos'], reducesConfidence: ['Unknown source', 'Concealed conditions', 'Aged piping'], requiredForStrongConfidence: ['photos'] },
  scopeOfWork: { standardSteps: ['Confirm the visible reported leak area.', ...PLUMBING_STANDARD_SCOPE, 'Remove the accessible failed component.', 'Prepare the visible connection area.', 'Install included repair components.', 'Document visible unresolved concerns.'], conditionalSteps: ['Create an included limited access opening where reviewed.', 'Recommend separate finish repair where surfaces are opened.'], cleanupSteps: PLUMBING_CLEANUP_SCOPE },
  recommendations: { relatedServices: ['Drywall Repair'], customerPreparation: ['Contact JBTRADESMENLLC directly for active flooding or an uncontrolled leak.'], professionalReviewTriggers: ['Active flooding', 'Source unknown', 'Concealed leak', 'Underground leak', 'Slab leak', 'Sewer backup', 'Gas line', 'Fire sprinkler', 'Roof leak', 'Mold-like growth', 'Structural damage', 'Multiple failures', 'Frozen system', 'No functioning shutoff', 'Commercial shutdown coordination', 'Permit uncertainty'] },
  assumptions: ['Leak is visible, accessible, localized, and reasonably identified.', 'Concealed conditions may change final scope and price.'], exclusions: ['Concealed, underground, slab, sewer, roof, gas, fire-suppression, or unresolved water-intrusion leaks', 'Finish-surface repair unless separately included'], permitsAndCode: PLUMBING_PERMIT_REVIEW, researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
