import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'
import { PLUMBING_CLEANUP_SCOPE, PLUMBING_DIRECT_CONTACT_MODIFIERS, PLUMBING_EQUIPMENT, PLUMBING_PERMIT_REVIEW, PLUMBING_STANDARD_SCOPE } from './plumbingShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const shutoffValveReplacement = {
  identity: { id: 'shutoff-valve-replacement', slug: 'shutoff-valve-replacement', version: '1.0.0', name: 'Shutoff Valve Replacement', shortName: 'Shutoff Valve', description: 'Replace accessible fixture-level or branch shutoff valves; main and utility-owned valves require review.', category: 'Plumbing', trade: 'plumbing', tags: ['shutoff valve', 'fixture valve', 'plumbing'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true }, crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 1, typical: 1.5, maximum: 3 }, quantityUnit: 'item', setupHours: 0.25, cleanupHours: 0.25, productionRate: { quantity: 1, unit: 'valve', laborHours: 1.5 }, returnVisits: { minimum: 1, typical: 1, maximum: 2 } },
  materials: { costRange: { minimum: 15, typical: 40, maximum: 125 }, costUnit: 'perItem', typicalMaterials: ['Replacement shutoff valve', 'Supply connector when included', 'Pipe-preparation materials', 'Approved fittings', 'Escutcheon where included', 'Thread-sealing material where appropriate', 'Protection materials'], wasteFactorPercentage: 0, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true }, equipment: PLUMBING_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 1.5, maximum: 6 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: true }, pricing: STANDARD_PRICING,
  estimatorQuestions: [question('valveCount', 'Number of valves', 'number', ['labor', 'materials'], true), question('fixtureServed', 'Fixture served', 'text', ['scope']), question('pipeMaterial', 'Pipe material', 'singleSelect', ['labor', 'manualReview'], true), question('valveType', 'Valve type', 'text', ['materials']), question('connectionType', 'Compression, threaded, soldered, push-to-connect, PEX, or unknown', 'singleSelect', ['labor', 'manualReview']), question('mainShutoffFunctioning', 'Main shutoff functioning', 'boolean', ['manualReview'], true), question('accessible', 'Accessible or concealed', 'boolean', ['manualReview']), question('visibleCorrosion', 'Corrosion', 'boolean', ['labor']), question('activeLeak', 'Leak active', 'boolean', ['manualReview']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, ...PLUMBING_DIRECT_CONTACT_MODIFIERS, { id: 'valve-additional', name: 'Additional accessible valves', description: 'Efficient quantity addition for similar valves.', conditions: [{ field: 'additionalValveCount', operator: 'greaterThan', value: 0 }], effects: { laborHoursPerUnit: { minimum: 0.5, typical: 1, maximum: 1.5 }, laborUnitField: 'additionalValveCount' }, customerExplanation: 'Similar accessible valves are scaled without repeating full setup.', internalNotes: [] }, { id: 'valve-corrosion', name: 'Heavy valve corrosion', description: 'Corrosion adjustment.', conditions: [{ field: 'visibleCorrosion', operator: 'equals', value: true }], effects: { laborMultiplier: 1.3 }, customerExplanation: 'Heavy corrosion may require additional removal time.', internalNotes: [] }, { id: 'valve-soldered', name: 'Soldered copper valve', description: 'Soldered copper adjustment.', conditions: [{ field: 'connectionType', operator: 'equals', value: 'soldered' }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Soldered copper connections require additional preparation.', internalNotes: [] }, { id: 'valve-cabinet', name: 'Cabinet access', description: 'Cabinet access adjustment.', conditions: [{ field: 'cabinetAccess', operator: 'equals', value: true }], effects: { laborMultiplier: 1.15 }, customerExplanation: 'Cabinet access may limit working space.', internalNotes: [] }, { id: 'valve-upstream', name: 'No working upstream shutoff', description: 'Upstream shutoff failure requires review.', conditions: [{ field: 'mainShutoffFunctioning', operator: 'equals', value: false }], effects: { requiresManualReview: true }, customerExplanation: 'A functioning upstream shutoff must be confirmed.', internalNotes: [] }, { id: 'valve-concealed', name: 'Concealed shutoff valve', description: 'Concealed piping requires review.', conditions: [{ field: 'accessible', operator: 'equals', value: false }], effects: { requiresManualReview: true }, customerExplanation: 'Concealed piping requires direct access review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Valve count', 'Pipe and connection type', 'Upstream shutoff status', 'Photos'], reducesConfidence: ['Unknown connection', 'Severe corrosion', 'No upstream shutoff'], requiredForStrongConfidence: ['photos'] },
  scopeOfWork: { standardSteps: [...PLUMBING_STANDARD_SCOPE, 'Remove the accessible existing valve.', 'Prepare the visible pipe end.', 'Install the approved replacement valve.', 'Connect the included supply line where applicable.', 'Operate the valve after restoring water.'], conditionalSteps: ['Document visible deteriorated piping or limited pipe-stub conditions.'], cleanupSteps: PLUMBING_CLEANUP_SCOPE },
  recommendations: { relatedServices: [], customerPreparation: ['Confirm the upstream shutoff location and access.'], professionalReviewTriggers: ['Main service valve', 'Utility-owned valve', 'No working upstream shutoff', 'Pipe embedded in wall', 'Severely deteriorated piping', 'Galvanized pipe', 'Valve breaks during removal', 'Active flooding', 'Commercial shutdown coordination', 'Permit or licensing uncertainty'] },
  assumptions: ['Profile applies only to accessible fixture-level or branch valves.', 'Existing upstream shutoff function is not assumed.'], exclusions: ['Main service valves', 'Utility-owned valves', 'Concealed piping access', 'Wall repair unless separately included'], permitsAndCode: PLUMBING_PERMIT_REVIEW, researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
