import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_EQUIPMENT, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const baseboardTrimRepair = {
  identity: { id: 'baseboard-trim-repair', slug: 'baseboard-trim-repair', version: '1.0.0', name: 'Baseboard and Trim Repair', shortName: 'Baseboard and Trim Repair', description: 'Repair or replace accessible interior baseboard and trim.', category: 'Interior Repairs', trade: 'carpentry', tags: ['baseboard', 'trim', 'carpentry'] },
  availability: { residential: true, commercial: true, emergencyEligible: false, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 1.5, typical: 4, maximum: 10 }, quantityUnit: 'linearFoot', setupHours: 0.5, cleanupHours: 0.5, productionRate: { quantity: 12, unit: 'linearFoot', laborHours: 1, unitsPerTechnicianHour: { minimum: 6, typical: 12, maximum: 20 } }, returnVisits: { minimum: 1, typical: 1, maximum: 2 } },
  materials: { costRange: { minimum: 2, typical: 5, maximum: 12 }, costUnit: 'perLinearFoot', typicalMaterials: ['Baseboard or trim stock', 'Fasteners', 'Wood filler', 'Caulk', 'Primer', 'Paint or stain when included', 'Surface protection'], wasteFactorPercentage: 15, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: STANDARD_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1.5, typical: 4, maximum: 10 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, dryingOrCuringTimeHours: { minimum: 1, typical: 4, maximum: 12 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: false },
  pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 15 },
  estimatorQuestions: [question('linearFeet', 'Linear feet', 'measurement', ['labor', 'materials', 'confidence'], true), question('repairOrReplacement', 'Repair or replacement', 'singleSelect', ['labor', 'materials', 'scope'], true), question('profileDimensions', 'Profile and dimensions', 'measurement', ['materials', 'confidence'], true), question('materialType', 'Material type', 'text', ['materials']), question('finishType', 'Paint or stain', 'singleSelect', ['labor', 'materials']), question('finishMatching', 'Matching existing trim', 'boolean', ['labor', 'materials', 'confidence']), question('wallDamagePresent', 'Wall damage present', 'boolean', ['scope', 'recommendations']), question('photos', 'Photos', 'photo', ['confidence'])],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, { id: 'trim-complex-profile', name: 'Complex trim profile', description: 'Complex profile adjustment.', conditions: [{ field: 'complexProfile', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'A complex trim profile requires additional fitting.', internalNotes: [] }, { id: 'trim-stain-grade', name: 'Stain-grade finish', description: 'Stain-grade finish adjustment.', conditions: [{ field: 'finishType', operator: 'equals', value: 'stain' }], effects: { laborMultiplier: 1.3 }, customerExplanation: 'Stain-grade work requires more detailed fitting and finish preparation.', internalNotes: [] }, { id: 'trim-paint-caulk', name: 'Paint and caulk included', description: 'Finish labor and material allowance.', conditions: [{ field: 'paintAndCaulkIncluded', operator: 'equals', value: true }], effects: { flatLaborHours: 2, flatMaterialCost: 45, scopeStepsToAdd: ['Caulk, prepare, and paint included repaired trim.'] }, customerExplanation: 'The range includes typical caulk and paint finishing.', internalNotes: ['Final labor addition ranges from one to four hours by quantity.'] }, { id: 'trim-water-pest', name: 'Water or pest damage', description: 'Underlying damage requires review.', conditions: [{ field: 'waterOrPestDamage', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'Water or pest damage may extend beyond visible trim.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Linear feet', 'Profile dimensions', 'Material identification', 'Photos'], reducesConfidence: ['Unknown profile', 'Unconfirmed damage source'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Inspect visible baseboard and trim conditions.', 'Protect adjacent surfaces.', 'Remove loose or damaged included material.', 'Prepare and fit repair or replacement pieces.', 'Fasten and fill included trim.'], conditionalSteps: ['Evaluate visible wall, water, or pest damage.', 'Match the existing profile where practical.', 'Caulk and finish included trim.'], cleanupSteps: ['Clean the work area.', 'Remove included repair debris.'] },
  recommendations: { relatedServices: ['Drywall repair', 'Interior painting'], customerPreparation: ['Provide a trim sample or profile measurements when available.'], professionalReviewTriggers: ['Water damage', 'Pest damage', 'Unavailable custom profile'] },
  assumptions: ['Minimum typical project materials remain subject to quantity and profile selection.', 'Work is limited to accessible non-structural trim.'], exclusions: ['Structural framing repair', 'Pest treatment', 'Active water-source repair'],
  permitsAndCode: { permitMayBeRequired: false, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: false, notes: [] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
