import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, ELEVATED_WORK_MODIFIERS, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const drywallRepair = {
  identity: { id: 'drywall-repair', slug: 'drywall-repair', version: '1.0.0', name: 'Drywall Repair', shortName: 'Drywall Repair', description: 'Repair accessible drywall holes, cracks, impact damage, and related finish areas.', category: 'Interior Repairs', trade: 'drywall', tags: ['drywall', 'patching', 'interior repair'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 2, typical: 4, maximum: 8 }, quantityUnit: 'repair', setupHours: 0.5, cleanupHours: 0.5, productionRate: { quantity: 1, unit: 'repair', laborHours: 4 }, returnVisits: { minimum: 1, typical: 2, maximum: 3 } },
  materials: { costRange: { minimum: 20, typical: 60, maximum: 175 }, costUnit: 'typicalProject', typicalMaterials: ['Drywall patch or gypsum board', 'Backing material', 'Joint tape', 'Joint compound', 'Fasteners', 'Sanding materials', 'Primer', 'Matching paint when included', 'Surface protection materials'], wasteFactorPercentage: 10, customerSuppliedAllowed: true, materialPickupUsuallyRequired: false, specialOrderPossible: true },
  equipment: { typicalEquipment: ['Drywall tools', 'Sanding equipment', 'Surface protection'], rentalMayBeRequired: true, rentalCostRange: { minimum: 0, typical: 50, maximum: 250 }, elevatedAccessPossible: true, specialtyEquipmentNotes: ['Scaffold or lift review may be required above ten feet.'] },
  timeline: { onsiteLaborHours: { minimum: 2, typical: 4, maximum: 8 }, calendarDurationDays: { minimum: 1, typical: 2, maximum: 4 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, dryingOrCuringTimeHours: { minimum: 4, typical: 12, maximum: 24 }, returnVisitRequired: true, weatherSensitive: false, permitMayAffectTimeline: false },
  pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 10 },
  estimatorQuestions: [question('damagedAreaCount', 'Number of damaged areas', 'number', ['labor', 'materials', 'timeline', 'confidence'], true), question('dimensions', 'Approximate dimensions', 'measurement', ['labor', 'materials', 'confidence'], true), question('surfaceLocation', 'Wall or ceiling', 'singleSelect', ['labor', 'equipment', 'timeline'], true), question('damageType', 'Hole, crack, impact, or water-related damage', 'singleSelect', ['scope', 'manualReview'], true), question('existingTexture', 'Existing texture', 'text', ['labor', 'materials', 'confidence']), question('paintIncluded', 'Paint included', 'boolean', ['labor', 'materials', 'scope']), question('paintMatchAvailable', 'Paint match available', 'boolean', ['confidence', 'materials']), question('ceilingHeightFeet', 'Height above floor', 'measurement', ['labor', 'equipment', 'manualReview']), question('photos', 'Photos', 'photo', ['confidence', 'scope']), question('damageSourceResolved', 'Is the source of damage resolved', 'boolean', ['manualReview', 'scope'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, ...ELEVATED_WORK_MODIFIERS, { id: 'drywall-texture-match', name: 'Texture matching', description: 'Existing texture must be matched.', conditions: [{ field: 'textureMatching', operator: 'equals', value: true }], effects: { laborMultiplier: 1.2, materialMultiplier: 1.1, scopeStepsToAdd: ['Prepare and match the existing texture where included.'] }, customerExplanation: 'Texture matching requires additional finish work.', internalNotes: [] }, { id: 'drywall-paint', name: 'Paint included', description: 'Prime and paint the repair area.', conditions: [{ field: 'paintIncluded', operator: 'equals', value: true }], effects: { flatLaborHours: 2, flatMaterialCost: 75, scopeStepsToAdd: ['Prime and apply finish paint where included.'] }, customerExplanation: 'The planning range includes finish painting.', internalNotes: ['Final hours vary from one to three based on repair quantity.'] }, { id: 'drywall-water', name: 'Water-related damage', description: 'Water-related damage needs source confirmation.', conditions: [{ field: 'damageType', operator: 'equals', value: 'water-related' }, { field: 'damageSourceResolved', operator: 'notEquals', value: true }], effects: { requiresManualReview: true, recommendationsToAdd: ['Confirm and repair the moisture source before closing the wall or ceiling.'] }, customerExplanation: 'Water-related damage requires source verification.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Dimensions', 'Damage-area count', 'Texture details', 'Photos', 'Confirmed damage source'], reducesConfidence: ['Unknown source', 'Missing photos', 'Unknown texture'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Protect surrounding surfaces.', 'Remove loose or damaged material.', 'Prepare the repair opening.', 'Install backing or replacement board where required.', 'Tape and finish joints.', 'Sand the repaired area.'], conditionalSteps: ['Evaluate visible water-related damage before closing the repair.', 'Match existing texture where included.', 'Prime the repaired surface where included.', 'Apply finish paint where included.'], cleanupSteps: ['Clean the work area.', 'Remove repair debris.'] },
  recommendations: { relatedServices: ['Interior painting'], customerPreparation: ['Clear accessible belongings from the repair area.', 'Provide available paint or finish information.'], professionalReviewTriggers: ['Active leak', 'Visible microbial growth', 'Sagging ceiling', 'Damage over 32 square feet', 'Possible structural damage', 'Asbestos-containing texture possibility', 'Height over 16 feet'] },
  assumptions: ['Damage is accessible and the source has been resolved before finish repair.', 'Standard one-technician crew unless access or safety review requires otherwise.'],
  exclusions: ['Active leak repair', 'Mold remediation', 'Structural repair', 'Asbestos testing or abatement'],
  permitsAndCode: { permitMayBeRequired: false, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: false, notes: ['Regulated materials or structural conditions require separate review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
