import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_EQUIPMENT, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const exteriorDoorRepairReplacement = {
  identity: { id: 'exterior-door-repair-replacement', slug: 'exterior-door-repair-replacement', version: '1.0.0', name: 'Exterior Door Repair or Replacement', shortName: 'Exterior Door Service', description: 'Repair or replace an accessible exterior door and included weather-sealing components.', category: 'Interior Repairs', trade: 'carpentry', tags: ['door', 'exterior', 'weather sealing'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 1.5, typical: 7, maximum: 16 }, quantityUnit: 'item', setupHours: 0.5, cleanupHours: 0.5, productionRate: { quantity: 1, unit: 'door', laborHours: 7 }, returnVisits: { minimum: 1, typical: 1, maximum: 3 } },
  materials: { costRange: { minimum: 20, typical: 500, maximum: 1600 }, costUnit: 'perItem', typicalMaterials: ['Door or repair components', 'Shims', 'Structural fasteners', 'Low-expansion foam', 'Exterior sealant', 'Flashing materials where required', 'Threshold components', 'Lockset when included', 'Interior and exterior trim when included'], wasteFactorPercentage: 10, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: STANDARD_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1.5, typical: 7, maximum: 16 }, calendarDurationDays: { minimum: 1, typical: 2, maximum: 4 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, dryingOrCuringTimeHours: { minimum: 1, typical: 4, maximum: 24 }, materialLeadTimeDays: { minimum: 0, typical: 5, maximum: 30 }, returnVisitRequired: false, weatherSensitive: true, permitMayAffectTimeline: true },
  pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 10 },
  estimatorQuestions: [question('repairOrReplacement', 'Repair or replacement', 'singleSelect', ['labor', 'materials', 'scope'], true), question('doorDimensions', 'Door dimensions', 'measurement', ['materials', 'confidence'], true), question('doorType', 'Door type', 'text', ['materials', 'manualReview'], true), question('frameCondition', 'Frame condition', 'singleSelect', ['labor', 'manualReview'], true), question('thresholdCondition', 'Threshold condition', 'singleSelect', ['labor', 'materials']), question('waterDamage', 'Water damage', 'boolean', ['scope', 'manualReview']), question('securityHardware', 'Security hardware', 'boolean', ['materials', 'manualReview']), question('finishRequired', 'Finish required', 'boolean', ['labor', 'materials']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, { id: 'exterior-door-replacement', name: 'Exterior door replacement', description: 'Replacement adjustment.', conditions: [{ field: 'repairOrReplacement', operator: 'equals', value: 'replacement' }], effects: { laborMultiplier: 1.5, materialMultiplier: 1.35, scopeStepsToAdd: ['Remove and replace the included exterior door assembly.'] }, customerExplanation: 'Exterior replacement requires fitting, sealing, and trim coordination.', internalNotes: [] }, { id: 'exterior-door-water', name: 'Exterior door water damage', description: 'Water damage requires source and substrate review.', conditions: [{ field: 'waterDamage', operator: 'equals', value: true }], effects: { requiresManualReview: true, recommendationsToAdd: ['Evaluate visible water intrusion and framing conditions before replacement.'] }, customerExplanation: 'Water damage may extend beyond the visible door components.', internalNotes: [] }, { id: 'exterior-door-specialty', name: 'Specialty exterior assembly', description: 'Specialty or regulated assembly review.', conditions: [{ field: 'specialtyDoor', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'This exterior assembly requires direct review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Door dimensions', 'Door type', 'Frame and threshold condition', 'Photos'], reducesConfidence: ['Water intrusion', 'Unknown frame condition', 'Custom opening'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Inspect visible door, frame, threshold, and seal conditions.', 'Protect adjacent finishes.', 'Repair accessible included components or remove the included door.', 'Fit and secure the included door.', 'Seal included accessible perimeter conditions.', 'Install included standard hardware.', 'Test normal operation.'], conditionalSteps: ['Evaluate visible water intrusion and rot.', 'Install included flashing, threshold, foam, and trim components.'], cleanupSteps: ['Clean the work area.', 'Remove included door-service debris.'] },
  recommendations: { relatedServices: ['Lock change', 'Window and trim repair', 'Exterior painting'], customerPreparation: ['Provide door dimensions, product selection, and hardware requirements.'], professionalReviewTriggers: ['Structural rot', 'Water intrusion', 'Custom openings', 'Storefront or aluminum commercial doors', 'Fire-rated assemblies', 'Permit uncertainty', 'Security-system integration'] },
  assumptions: ['The existing opening remains structurally suitable unless visible review indicates otherwise.'], exclusions: ['Structural reconstruction', 'Storefront systems', 'Fire-rated certification', 'Security-system integration'],
  permitsAndCode: { permitMayBeRequired: true, inspectionMayBeRequired: true, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: true, notes: ['Rated assemblies, structural changes, and local replacement rules require review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
