import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_EQUIPMENT, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const interiorDoorRepairReplacement = {
  identity: { id: 'interior-door-repair-replacement', slug: 'interior-door-repair-replacement', version: '1.0.0', name: 'Interior Door Repair or Replacement', shortName: 'Interior Door Service', description: 'Repair or replace an accessible interior door and included hardware or trim.', category: 'Interior Repairs', trade: 'carpentry', tags: ['door', 'interior', 'carpentry'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 1, typical: 4, maximum: 10 }, quantityUnit: 'item', setupHours: 0.25, cleanupHours: 0.5, productionRate: { quantity: 1, unit: 'door', laborHours: 4 }, returnVisits: { minimum: 1, typical: 1, maximum: 2 } },
  materials: { costRange: { minimum: 10, typical: 275, maximum: 750 }, costUnit: 'perItem', typicalMaterials: ['Door repair components or door slab', 'Shims', 'Fasteners', 'Hardware when included', 'Interior trim', 'Filler', 'Paint or stain when included'], wasteFactorPercentage: 10, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: STANDARD_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 4, maximum: 10 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 3, maximum: 21 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: true },
  pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 10 },
  estimatorQuestions: [question('repairOrReplacement', 'Repair or replacement', 'singleSelect', ['labor', 'materials', 'scope'], true), question('doorAssembly', 'Slab or prehung', 'singleSelect', ['labor', 'materials', 'timeline']), question('doorDimensions', 'Door dimensions', 'measurement', ['materials', 'confidence'], true), question('doorCore', 'Hollow core or solid core', 'singleSelect', ['materials']), question('frameCondition', 'Frame condition', 'singleSelect', ['labor', 'manualReview'], true), question('hardwareIncluded', 'Hardware included', 'boolean', ['labor', 'materials']), question('finishRequired', 'Paint or stain', 'singleSelect', ['labor', 'materials']), question('wallTrimDamage', 'Wall or trim damage', 'boolean', ['scope', 'recommendations']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, { id: 'door-slab', name: 'Door slab replacement', description: 'Slab replacement planning adjustment.', conditions: [{ field: 'doorAssembly', operator: 'equals', value: 'slab' }], effects: { laborMultiplier: 1.5, materialMultiplier: 1.2 }, customerExplanation: 'A slab replacement requires fitting and hardware preparation.', internalNotes: ['Profile planning band: two to seven labor hours and $100–$450 materials.'] }, { id: 'door-prehung', name: 'Prehung door replacement', description: 'Prehung replacement planning adjustment.', conditions: [{ field: 'doorAssembly', operator: 'equals', value: 'prehung' }], effects: { laborMultiplier: 2, materialMultiplier: 1.5, scopeStepsToAdd: ['Remove and replace the included prehung door assembly.'] }, customerExplanation: 'A prehung replacement includes frame removal, fitting, and trim coordination.', internalNotes: ['Profile planning band: four to ten labor hours and $200–$750 materials.'] }, { id: 'door-specialty', name: 'Specialty door review', description: 'Specialty assembly requires review.', conditions: [{ field: 'specialtyDoor', operator: 'equals', value: true }], effects: { requiresManualReview: true }, customerExplanation: 'The door type or opening requires direct review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Door dimensions', 'Assembly type', 'Frame condition', 'Photos'], reducesConfidence: ['Unknown frame condition', 'Custom sizing'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Inspect visible door, frame, and hardware conditions.', 'Protect adjacent finishes.', 'Repair accessible included components or remove the included door.', 'Fit and adjust the included door.', 'Install included standard hardware.', 'Test normal door operation.'], conditionalSteps: ['Evaluate visible frame, wall, and trim damage.', 'Prepare included paint or stain finish.'], cleanupSteps: ['Clean the work area.', 'Remove included door-service debris.'] },
  recommendations: { relatedServices: ['Baseboard and trim repair', 'Interior painting', 'Lock change'], customerPreparation: ['Provide door measurements and hardware selections.'], professionalReviewTriggers: ['Structural opening changes', 'Fire-rated door', 'Commercial rated assembly', 'Pocket door', 'Significant framing damage', 'Custom-sized door'] },
  assumptions: ['The existing opening remains structurally suitable unless otherwise identified.'], exclusions: ['Structural opening changes', 'Fire-rated certification', 'Access-control integration'],
  permitsAndCode: { permitMayBeRequired: true, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: true, notes: ['Rated assemblies and opening changes require jurisdiction review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
