import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, ELEVATED_WORK_MODIFIERS, FINISH_MATCHING_MODIFIER, NATIONALLY_INFORMED_RESEARCH, STANDARD_CREW, STANDARD_PRICING, question } from '../profileShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const windowTrimRepair = {
  identity: { id: 'window-trim-repair', slug: 'window-trim-repair', version: '1.0.0', name: 'Window and Trim Repair', shortName: 'Window Trim Repair', description: 'Repair accessible interior or exterior window trim and included sealant or finish areas.', category: 'Interior Repairs', trade: 'carpentry', tags: ['window trim', 'carpentry', 'caulking'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true },
  crew: STANDARD_CREW,
  labor: { baseHours: { minimum: 2, typical: 5, maximum: 12 }, quantityUnit: 'item', setupHours: 0.5, cleanupHours: 0.5, productionRate: { quantity: 1, unit: 'window', laborHours: 5 }, returnVisits: { minimum: 1, typical: 1, maximum: 3 } },
  materials: { costRange: { minimum: 25, typical: 125, maximum: 500 }, costUnit: 'typicalProject', typicalMaterials: ['Trim stock', 'Repair lumber or composite material', 'Fasteners', 'Exterior or interior sealant', 'Filler', 'Primer', 'Paint when included'], wasteFactorPercentage: 15, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: { typicalEquipment: ['Carpentry tools', 'Ladders', 'Surface protection'], rentalMayBeRequired: true, rentalCostRange: { minimum: 0, typical: 100, maximum: 600 }, elevatedAccessPossible: true, specialtyEquipmentNotes: ['Second-story and high-access work may require scaffold or lift review.'] },
  timeline: { onsiteLaborHours: { minimum: 2, typical: 5, maximum: 12 }, calendarDurationDays: { minimum: 1, typical: 2, maximum: 4 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, dryingOrCuringTimeHours: { minimum: 1, typical: 4, maximum: 24 }, materialLeadTimeDays: { minimum: 0, typical: 3, maximum: 21 }, returnVisitRequired: false, weatherSensitive: true, permitMayAffectTimeline: true },
  pricing: { ...STANDARD_PRICING, wasteFactorPercentage: 15 },
  estimatorQuestions: [question('trimLocation', 'Interior or exterior trim', 'singleSelect', ['labor', 'materials', 'timeline'], true), question('windowCount', 'Number of windows', 'number', ['labor', 'materials'], true), question('linearFeet', 'Linear feet', 'measurement', ['labor', 'materials', 'confidence']), question('materialType', 'Material type', 'text', ['materials']), question('rotOrWaterDamage', 'Rot or water damage', 'boolean', ['manualReview', 'scope']), question('caulkingRequired', 'Caulking required', 'boolean', ['labor', 'materials']), question('paintIncluded', 'Paint required', 'boolean', ['labor', 'materials']), question('operationAffected', 'Window operation affected', 'boolean', ['manualReview']), question('ceilingHeightFeet', 'Height', 'measurement', ['labor', 'equipment', 'manualReview']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, FINISH_MATCHING_MODIFIER, ...ELEVATED_WORK_MODIFIERS, { id: 'window-exterior', name: 'Exterior window trim', description: 'Exterior work adjustment.', conditions: [{ field: 'trimLocation', operator: 'equals', value: 'exterior' }], effects: { laborMultiplier: 1.15, scopeStepsToAdd: ['Prepare and seal included accessible exterior trim conditions.'] }, customerExplanation: 'Exterior trim requires weather-resistant preparation and sealing.', internalNotes: [] }, { id: 'window-rot', name: 'Window trim rot repair', description: 'Visible rot adjustment and review.', conditions: [{ field: 'rotOrWaterDamage', operator: 'equals', value: true }], effects: { laborMultiplier: 1.3, requiresManualReview: true, recommendationsToAdd: ['Evaluate visible moisture sources and substrate conditions.'] }, customerExplanation: 'Rot or water damage may extend beyond visible trim.', internalNotes: [] }, { id: 'window-paint', name: 'Window trim paint included', description: 'Paint finish allowance.', conditions: [{ field: 'paintIncluded', operator: 'equals', value: true }], effects: { flatLaborHours: 2, flatMaterialCost: 50, scopeStepsToAdd: ['Prime and paint included repaired trim.'] }, customerExplanation: 'The range includes typical paint finishing.', internalNotes: ['Approved planning addition is one to four hours; typical two-hour addition used.'] }, { id: 'window-second-story', name: 'Second-story window trim', description: 'Second-story access adjustment.', conditions: [{ field: 'floorLevel', operator: 'greaterThan', value: 1 }], effects: { laborMultiplier: 1.25, recommendationsToAdd: ['Confirm elevated-access equipment requirements.'] }, customerExplanation: 'Second-story access requires additional setup.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Window count', 'Linear feet', 'Material type', 'Photos'], reducesConfidence: ['Unknown moisture source', 'Unknown height', 'Missing photos'], requiredForStrongConfidence: ['measurements', 'photos'] },
  scopeOfWork: { standardSteps: ['Inspect visible window trim and adjacent accessible conditions.', 'Protect adjacent finishes.', 'Remove loose or damaged included trim.', 'Prepare and install included repair material.', 'Fasten, fill, and seal included trim.'], conditionalSteps: ['Evaluate visible rot and water intrusion.', 'Test normal window operation without diagnosing concealed conditions.', 'Prime and paint included repaired trim.'], cleanupSteps: ['Clean the work area.', 'Remove included repair debris.'] },
  recommendations: { relatedServices: ['Exterior painting', 'Interior painting'], customerPreparation: ['Provide clear access and available trim or paint information.'], professionalReviewTriggers: ['Active leaks', 'Failed insulated glass', 'Structural framing damage', 'Lead paint possibility', 'Full window replacement', 'Height over 16 feet'] },
  assumptions: ['Repair is limited to accessible trim and non-structural visible conditions.'], exclusions: ['Full window replacement', 'Insulated-glass replacement', 'Structural framing reconstruction', 'Lead abatement'],
  permitsAndCode: { permitMayBeRequired: true, inspectionMayBeRequired: false, licensedTradeMayBeRequired: false, jurisdictionReviewRequired: true, notes: ['Full replacement or structural changes require separate review.'] },
  researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
