import { COMPANY_STANDARDS } from '../company/companyStandards'
import type { PropertyContext, ServiceTiming } from '../types/v1/company'
import type { NumericRange } from '../types/v1/pricing'

export type CategoryFallbackId = 'residentialRepair'|'commercialRepair'|'residentialMaintenance'|'commercialMaintenance'|'residentialRemodel'|'commercialTenantImprovement'|'residentialAppliance'|'commercialAppliance'|'propertyAssessment'|'residentialOther'|'commercialOther'|'residentialPlumbing'|'commercialPlumbing'|'residentialFlooring'|'commercialFlooring'|'residentialEmergencyDiagnostic'|'commercialEmergencyDiagnostic'
export type FallbackResultKind = 'broad' | 'diagnostic' | 'assessment' | 'emergency'

export interface CategoryFallbackDefinition {
  id: CategoryFallbackId
  heading: 'Broad Preliminary Planning Range' | 'Preliminary Diagnostic Range' | 'Emergency Diagnostic / Initial Service Range'
  label: string
  kind: FallbackResultKind
  laborHours: NumericRange
  materials: NumericRange
  visits: NumericRange
  duration: string
  assumptions: readonly string[]
  recommendations: readonly string[]
  basisNote: string
}

const range = (minimum: number, typical: number, maximum: number): NumericRange => ({ minimum, typical, maximum })
const BROAD_NOTE = 'This broad planning range uses category-level assumptions because the exact project scope, quantity, materials, or site conditions are not yet fully defined.'
const DIAGNOSTIC_NOTE = 'This range covers preliminary diagnostic or initial service time and does not guarantee that the complete repair is included.'

export const CATEGORY_FALLBACK_PRICING: Readonly<Record<CategoryFallbackId, CategoryFallbackDefinition>> = {
  residentialRepair: { id: 'residentialRepair', heading: 'Broad Preliminary Planning Range', label: 'Residential Repair Planning Range', kind: 'broad', laborHours: range(2, 5, 8), materials: range(25, 200, 500), visits: range(1, 1, 2), duration: 'Initial service through approximately three working days', assumptions: ['One technician', 'Accessible repair conditions', 'No major regulated, structural, or concealed scope included'], recommendations: ['Confirm scope, measurements, materials, and site conditions through professional review.'], basisNote: BROAD_NOTE },
  commercialRepair: { id: 'commercialRepair', heading: 'Broad Preliminary Planning Range', label: 'Commercial Repair Planning Range', kind: 'broad', laborHours: range(2, 6, 12), materials: range(50, 400, 1000), visits: range(1, 1, 2), duration: 'Initial service through approximately four working days', assumptions: ['One technician', 'Accessible light-commercial repair conditions', 'No major regulated or capital-improvement scope included'], recommendations: ['Confirm access, work-zone coordination, materials, and final scope.'], basisNote: BROAD_NOTE },
  residentialMaintenance: { id: 'residentialMaintenance', heading: 'Broad Preliminary Planning Range', label: 'Residential Maintenance Planning Range', kind: 'broad', laborHours: range(1, 3, 6), materials: range(0, 125, 350), visits: range(1, 1, 1), duration: 'Usually one maintenance visit', assumptions: ['One technician', 'Routine accessible maintenance tasks'], recommendations: ['Provide an itemized maintenance list before scheduling.'], basisNote: BROAD_NOTE },
  commercialMaintenance: { id: 'commercialMaintenance', heading: 'Broad Preliminary Planning Range', label: 'Commercial Maintenance Planning Range', kind: 'broad', laborHours: range(2, 5, 10), materials: range(25, 300, 750), visits: range(1, 1, 2), duration: 'One to two planned maintenance visits', assumptions: ['One technician', 'Routine accessible facility maintenance'], recommendations: ['Provide an itemized scope and access requirements.'], basisNote: BROAD_NOTE },
  residentialRemodel: { id: 'residentialRemodel', heading: 'Broad Preliminary Planning Range', label: 'Broad Remodel Planning Range', kind: 'broad', laborHours: range(24, 80, 160), materials: range(1000, 7500, 20000), visits: range(2, 3, 6), duration: 'Multi-visit project; schedule requires professional assessment', assumptions: ['One-technician-hour pricing basis', 'Planning total includes an assumed 2–6 site visits', 'Design, selections, permits, specialty trades, and concealed conditions remain unconfirmed'], recommendations: ['Schedule a professional assessment for a defined remodel scope and formal estimate.'], basisNote: BROAD_NOTE },
  commercialTenantImprovement: { id: 'commercialTenantImprovement', heading: 'Broad Preliminary Planning Range', label: 'Commercial Tenant-Improvement Planning Range', kind: 'broad', laborHours: range(40, 120, 240), materials: range(2500, 15000, 40000), visits: range(3, 5, 10), duration: 'Multi-visit project; schedule requires professional assessment', assumptions: ['One-technician-hour pricing basis', 'Planning total includes an assumed 3–10 site visits', 'Design, phasing, permits, specialty trades, and occupancy coordination remain unconfirmed'], recommendations: ['Schedule a professional assessment for plans, phasing, permits, and a formal estimate.'], basisNote: BROAD_NOTE },
  residentialAppliance: { id: 'residentialAppliance', heading: 'Preliminary Diagnostic Range', label: 'Residential Appliance Diagnostic / Initial-Service Range', kind: 'diagnostic', laborHours: range(1, 2, 4), materials: range(0, 150, 400), visits: range(1, 1, 2), duration: 'Initial diagnostic visit; a return visit may be required', assumptions: ['Accessible residential appliance or equipment', 'Parts and complete repair scope are not confirmed'], recommendations: ['Provide manufacturer, model, symptoms, and photos before scheduling.'], basisNote: DIAGNOSTIC_NOTE },
  commercialAppliance: { id: 'commercialAppliance', heading: 'Preliminary Diagnostic Range', label: 'Commercial Appliance or Equipment Diagnostic Range', kind: 'diagnostic', laborHours: range(2, 4, 6), materials: range(0, 300, 750), visits: range(1, 1, 2), duration: 'Initial diagnostic visit; a return visit may be required', assumptions: ['Accessible light-commercial appliance or equipment', 'Parts and complete repair scope are not confirmed'], recommendations: ['Provide manufacturer, model, symptoms, access requirements, and photos.'], basisNote: DIAGNOSTIC_NOTE },
  propertyAssessment: { id: 'propertyAssessment', heading: 'Preliminary Diagnostic Range', label: 'Property Assessment Service Range', kind: 'assessment', laborHours: range(1, 2, 4), materials: range(0, 0, 0), visits: range(1, 1, 1), duration: 'One assessment visit', assumptions: ['Accessible visual planning assessment only', 'This is not repair pricing, a code inspection, or a guarantee that concealed conditions will be identified'], recommendations: ['Schedule the professional assessment and provide known concerns and photos.'], basisNote: DIAGNOSTIC_NOTE },
  residentialOther: { id: 'residentialOther', heading: 'Broad Preliminary Planning Range', label: 'General Residential Planning Range', kind: 'broad', laborHours: range(1, 4, 8), materials: range(0, 200, 500), visits: range(1, 1, 2), duration: 'Initial service; additional visits may be required', assumptions: ['One technician', 'Small accessible residential scope'], recommendations: ['Clarify the service, measurements, materials, and condition through professional review.'], basisNote: BROAD_NOTE },
  commercialOther: { id: 'commercialOther', heading: 'Broad Preliminary Planning Range', label: 'General Commercial Planning Range', kind: 'broad', laborHours: range(2, 6, 12), materials: range(0, 400, 1000), visits: range(1, 1, 2), duration: 'Initial service; additional visits may be required', assumptions: ['One technician', 'Small accessible light-commercial scope'], recommendations: ['Clarify the service, access, measurements, materials, and condition through professional review.'], basisNote: BROAD_NOTE },
  residentialPlumbing: { id: 'residentialPlumbing', heading: 'Preliminary Diagnostic Range', label: 'Preliminary Plumbing Service Range — Final Scope Requires Review', kind: 'diagnostic', laborHours: range(2, 4, 6), materials: range(25, 200, 500), visits: range(1, 1, 2), duration: 'Initial plumbing service; a return visit may be required', assumptions: ['Accessible residential plumbing service', 'Concealed piping and complete repair scope are not confirmed'], recommendations: ['Provide fixture, symptom, access, and leak details with photos.'], basisNote: DIAGNOSTIC_NOTE },
  commercialPlumbing: { id: 'commercialPlumbing', heading: 'Preliminary Diagnostic Range', label: 'Preliminary Plumbing Service Range — Final Scope Requires Review', kind: 'diagnostic', laborHours: range(2, 5, 10), materials: range(50, 400, 1000), visits: range(1, 1, 2), duration: 'Initial plumbing service; a return visit may be required', assumptions: ['Accessible light-commercial plumbing service', 'Concealed piping, shutdown coordination, and complete repair scope are not confirmed'], recommendations: ['Provide fixture, symptom, shutdown, access, and leak details with photos.'], basisNote: DIAGNOSTIC_NOTE },
  residentialFlooring: { id: 'residentialFlooring', heading: 'Broad Preliminary Planning Range', label: 'Broad Flooring Planning Range — Flooring type and measurements will affect final pricing', kind: 'broad', laborHours: range(8, 20, 40), materials: range(500, 2500, 6000), visits: range(1, 2, 3), duration: 'Multi-day flooring project; final duration depends on product and measurements', assumptions: ['One-technician-hour pricing basis', 'Flooring type, substrate, removal, layout, and measurements remain unconfirmed'], recommendations: ['Provide square footage, flooring selection, substrate details, and photos.'], basisNote: BROAD_NOTE },
  commercialFlooring: { id: 'commercialFlooring', heading: 'Broad Preliminary Planning Range', label: 'Broad Flooring Planning Range — Flooring type and measurements will affect final pricing', kind: 'broad', laborHours: range(12, 40, 80), materials: range(1000, 6000, 15000), visits: range(1, 2, 5), duration: 'Multi-day flooring project; final duration depends on product, phasing, and measurements', assumptions: ['One-technician-hour pricing basis', 'Flooring type, substrate, removal, layout, phasing, and measurements remain unconfirmed'], recommendations: ['Provide square footage, flooring selection, substrate, occupancy, phasing, and photos.'], basisNote: BROAD_NOTE },
  residentialEmergencyDiagnostic: { id: 'residentialEmergencyDiagnostic', heading: 'Emergency Diagnostic / Initial Service Range', label: 'Emergency Diagnostic / Initial Service Range', kind: 'emergency', laborHours: range(1, 2, 4), materials: range(0, 0, 0), visits: range(1, 1, 1), duration: 'Initial emergency diagnostic or service call; availability requires direct confirmation', assumptions: ['Range covers initial diagnostic or service-call time before parts', 'Complete repair is not included or guaranteed'], recommendations: ['Contact the appropriate utility, emergency service, or qualified professional based on the observed condition.'], basisNote: DIAGNOSTIC_NOTE },
  commercialEmergencyDiagnostic: { id: 'commercialEmergencyDiagnostic', heading: 'Emergency Diagnostic / Initial Service Range', label: 'Emergency Diagnostic / Initial Service Range', kind: 'emergency', laborHours: range(1, 2, 4), materials: range(0, 0, 0), visits: range(1, 1, 1), duration: 'Initial emergency diagnostic or service call; availability requires direct confirmation', assumptions: ['Range covers initial diagnostic or service-call time before parts', 'Complete repair is not included or guaranteed'], recommendations: ['Contact the appropriate utility, emergency service, or qualified professional based on the observed condition.'], basisNote: DIAGNOSTIC_NOTE },
}

export function fallbackLaborRate(context: PropertyContext, timing: ServiceTiming, forceEmergency = false): number {
  const emergency = forceEmergency || timing === 'emergency' || timing === 'afterHours'
  if (context === 'commercial') return emergency ? COMPANY_STANDARDS.laborRates.commercialEmergency : COMPANY_STANDARDS.laborRates.commercial
  return emergency ? COMPANY_STANDARDS.laborRates.residentialEmergency : COMPANY_STANDARDS.laborRates.residential
}

export const FALLBACK_TRIP_CHARGE_PER_VISIT = COMPANY_STANDARDS.billing.tripChargePerVisit
