import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, OCCUPIED_PROTECTION_MODIFIER, STANDARD_PRICING, question } from '../profileShared'
import { ELECTRICAL_CLEANUP_SCOPE, ELECTRICAL_EQUIPMENT, ELECTRICAL_MANUAL_REVIEW_MODIFIERS, ELECTRICAL_PERMIT_REVIEW, ELECTRICAL_SAFETY_OVERRIDE_MODIFIERS } from './electricalShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const electricalTroubleshooting = {
  identity: { id: 'electrical-troubleshooting', slug: 'electrical-troubleshooting', version: '1.0.0', name: 'Electrical Troubleshooting', shortName: 'Electrical Diagnostics', description: 'Preliminary troubleshooting of accessible branch-circuit symptoms without guaranteeing full diagnosis or repair during the initial service period.', category: 'Electrical', trade: 'electrical', tags: ['diagnostics', 'troubleshooting', 'branch circuit'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true }, crew: { defaultSize: 1, minimumSize: 1, maximumRecommendedSize: 2, secondTechnicianRequired: false, secondTechnicianReason: null },
  labor: { baseHours: { minimum: 1, typical: 2, maximum: 4 }, quantityUnit: 'diagnosticVisit', setupHours: 0.25, cleanupHours: 0.25, returnVisits: { minimum: 1, typical: 1, maximum: 3 }, minimumBillableHoursOverride: 1 },
  materials: { costRange: { minimum: 0, typical: 15, maximum: 75 }, costUnit: 'typicalProject', costComponents: [{ name: 'Diagnostic visit consumables', costRange: { minimum: 0, typical: 15, maximum: 75 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false }, { name: 'Authorized accessible minor repair components', costRange: { minimum: 10, typical: 75, maximum: 350 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false, conditions: [{ field: 'minorRepairAuthorized', operator: 'equals', value: true }] }], typicalMaterials: ['Replacement standard device where authorized', 'Approved wire connectors', 'Accessible minor repair components', 'Labels', 'Fasteners', 'Protection materials'], wasteFactorPercentage: 0, customerSuppliedAllowed: false, materialPickupUsuallyRequired: false, specialOrderPossible: true }, equipment: ELECTRICAL_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 3, maximum: 12 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 3 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 3, maximum: 21 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: true }, pricing: STANDARD_PRICING,
  estimatorQuestions: [question('propertyType', 'Residential or commercial', 'singleSelect', ['scope']), question('symptomDescription', 'Symptom description', 'textarea', ['confidence'], true), question('symptomType', 'Loss of power, intermittent issue, flickering, tripping, heat, odor, sparking, or damaged device', 'multiSelect', ['labor', 'manualReview'], true), question('affectedLocationCount', 'Number of affected rooms or devices', 'number', ['labor']), question('repeatedBreakerTrips', 'Breaker trips', 'boolean', ['manualReview']), question('protectionTrips', 'GFCI or AFCI trips', 'boolean', ['confidence']), question('recentRenovations', 'Recent renovations', 'boolean', ['confidence']), question('recentWaterLeak', 'Recent water leak', 'boolean', ['manualReview']), question('intermittentIssue', 'Issue intermittent', 'boolean', ['labor', 'confidence']), question('circuitLabelKnown', 'Circuit label known', 'boolean', ['confidence']), question('panelTypeKnown', 'Panel type known', 'boolean', ['confidence']), question('aluminumWiring', 'Aluminum wiring possibility', 'boolean', ['manualReview']), question('knobAndTubeWiring', 'Knob-and-tube possibility', 'boolean', ['manualReview']), question('burningOdor', 'Burning smell', 'boolean', ['manualReview']), question('smoke', 'Smoke', 'boolean', ['manualReview']), question('waterContactingElectrical', 'Water contacting electrical equipment', 'boolean', ['manualReview']), question('activeArcing', 'Active sparking or arcing', 'boolean', ['manualReview']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, OCCUPIED_PROTECTION_MODIFIER, ...ELECTRICAL_MANUAL_REVIEW_MODIFIERS, ...ELECTRICAL_SAFETY_OVERRIDE_MODIFIERS,
    { id: 'diagnostic-extended', name: 'Extended branch-circuit troubleshooting', description: 'Extended diagnostic labor mode.', conditions: [{ field: 'extendedTroubleshooting', operator: 'equals', value: true }], effects: { laborHoursOverride: { minimum: 3, typical: 6, maximum: 12 } }, customerExplanation: 'The described symptoms may require an extended diagnostic period.', internalNotes: [] },
    { id: 'diagnostic-intermittent', name: 'Intermittent fault', description: 'Intermittent symptom adjustment.', conditions: [{ field: 'intermittentIssue', operator: 'equals', value: true }], effects: { laborMultiplier: 1.25, confidenceAdjustment: -10 }, customerExplanation: 'Intermittent faults can require additional observation and reduce preliminary confidence.', internalNotes: [] },
    { id: 'diagnostic-multiple-rooms', name: 'Multiple affected rooms', description: 'Multi-location diagnostic adjustment.', conditions: [{ field: 'affectedLocationCount', operator: 'greaterThan', value: 1 }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Symptoms across multiple locations require additional diagnostic time.', internalNotes: [] },
    { id: 'diagnostic-poor-labeling', name: 'Poor circuit labeling', description: 'Circuit-identification adjustment.', conditions: [{ field: 'circuitLabelKnown', operator: 'equals', value: false }], effects: { laborMultiplier: 1.15 }, customerExplanation: 'Unknown circuit labeling can require additional identification time.', internalNotes: [] },
    { id: 'diagnostic-water', name: 'Recent water exposure', description: 'Water exposure requires manual review.', conditions: [{ field: 'recentWaterLeak', operator: 'equals', value: true }], effects: { requiresManualReview: true, manualReviewFlags: ['electricalProfessionalReviewRequired'], recommendationsToAdd: ['Do not handle affected electrical equipment; arrange qualified review.'] }, customerExplanation: 'Recent water exposure requires direct safety review.', internalNotes: [] },
    { id: 'diagnostic-unrelated', name: 'Multiple unrelated symptoms', description: 'Unrelated symptoms require direct review.', conditions: [{ field: 'multipleUnrelatedSymptoms', operator: 'equals', value: true }], effects: { requiresManualReview: true, manualReviewFlags: ['electricalProfessionalReviewRequired'] }, customerExplanation: 'Multiple unrelated symptoms require direct diagnostic review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Detailed symptom description', 'Exact affected locations', 'Photos when damage is visible', 'Breaker behavior', 'Access information', 'Recent-change information'], reducesConfidence: ['Unknown or intermittent symptoms', 'Unknown circuit labels', 'Multiple unrelated symptoms'], requiredForStrongConfidence: ['symptomDescription', 'symptomType', 'photos'] },
  scopeOfWork: { standardSteps: ['Review reported symptoms.', 'Inspect accessible affected areas and confirm safe access conditions.', 'Perform applicable non-destructive diagnostic checks.', 'Evaluate accessible devices and branch-circuit behavior.', 'Identify visible or testable probable causes where possible.', 'Document unresolved conditions and provide a repair or manual-review recommendation.', 'Complete an authorized accessible minor repair only when included.', 'Test normal operation when an included repair is completed.'], conditionalSteps: [], cleanupSteps: ELECTRICAL_CLEANUP_SCOPE },
  recommendations: { relatedServices: [], customerPreparation: ['Diagnostic labor identifies and narrows visible or testable causes. Repair scope and final pricing may change after the cause is identified.', 'Do not remove panel covers or touch energized components.'], professionalReviewTriggers: ['Smoke, active arcing, burning odor, melted components, hot equipment, shock report, or water contacting electrical equipment', 'Repeated main-breaker trip', 'Service entrance, utility equipment, or panel damage', 'Aluminum or knob-and-tube wiring', 'Commercial three-phase, life-safety, fire-alarm, generator, solar, or EV systems', 'Uncontrolled energized condition', 'Permit or licensing uncertainty'] },
  assumptions: ['Safe access is available for non-destructive checks.', 'The reported issue is limited to accessible branch-circuit symptoms.'], exclusions: ['Utility-owned equipment', 'Service entrance or main panels', 'Life-safety, generator-transfer, solar, three-phase, industrial, or high-voltage systems', 'Underground or extensive concealed wiring faults', 'Guaranteed diagnosis or repair during the initial period'], permitsAndCode: ELECTRICAL_PERMIT_REVIEW, researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
