import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, OCCUPIED_PROTECTION_MODIFIER, STANDARD_PRICING, question } from '../profileShared'
import { ELECTRICAL_CLEANUP_SCOPE, ELECTRICAL_EQUIPMENT, ELECTRICAL_MANUAL_REVIEW_MODIFIERS, ELECTRICAL_PERMIT_REVIEW, ELECTRICAL_SAFETY_OVERRIDE_MODIFIERS, ELECTRICAL_STANDARD_SCOPE } from './electricalShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const lightFixtureReplacement = {
  identity: { id: 'light-fixture-replacement', slug: 'light-fixture-replacement', version: '1.0.0', name: 'Light Fixture Replacement', shortName: 'Light Fixture', description: 'Accessible, like-for-like replacement of an existing light fixture using the existing electrical box and circuit.', category: 'Electrical', trade: 'electrical', tags: ['lighting', 'fixture replacement', 'electrical'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true },
  crew: { defaultSize: 1, minimumSize: 1, maximumRecommendedSize: 2, secondTechnicianRequired: false, secondTechnicianReason: 'Large, heavy, fragile, elevated, or occupied-commercial fixture work may require a second technician.' },
  labor: { baseHours: { minimum: 1, typical: 1.5, maximum: 3 }, quantityUnit: 'fixture', setupHours: 0.25, cleanupHours: 0.5, productionRate: { quantity: 1, unit: 'fixture', laborHours: 1, unitsPerTechnicianHour: { minimum: 0.5, typical: 1, maximum: 2 } }, returnVisits: { minimum: 1, typical: 1, maximum: 2 }, minimumBillableHoursOverride: 1 },
  materials: { costRange: { minimum: 10, typical: 40, maximum: 175 }, costUnit: 'typicalProject', costComponents: [{ name: 'Connection, mounting, and consumable materials', costRange: { minimum: 10, typical: 40, maximum: 175 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false }, { name: 'Contractor-supplied fixture allowance', costRange: { minimum: 40, typical: 175, maximum: 800 }, costUnit: 'perItem', customerSuppliedEligible: true, applyWasteFactor: false }], typicalMaterials: ['Replacement fixture', 'Approved mounting hardware', 'Fixture-rated fasteners', 'Wire connectors', 'Grounding components where applicable', 'Canopy hardware', 'Replacement electrical box where minor and approved', 'Ceiling medallion when included', 'Protection materials', 'Disposable testing and cleanup materials'], wasteFactorPercentage: 0, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: ELECTRICAL_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 4, maximum: 8 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 1 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 7, maximum: 21 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: true },
  pricing: STANDARD_PRICING,
  estimatorQuestions: [question('fixtureCount', 'Number of fixtures', 'number', ['labor', 'materials'], true), question('exposure', 'Interior or exterior', 'singleSelect', ['labor', 'materials'], true), question('mountingLocation', 'Ceiling or wall mounted', 'singleSelect', ['scope']), question('existingFixtureType', 'Existing fixture type', 'text', ['confidence']), question('replacementFixtureType', 'Replacement fixture type', 'text', ['labor', 'confidence']), question('ceilingHeightFeet', 'Ceiling height', 'number', ['labor', 'manualReview'], true), question('fixtureWeightPounds', 'Approximate fixture weight', 'number', ['labor', 'manualReview']), question('fixtureDimensions', 'Fixture dimensions', 'text', ['confidence']), question('existingBoxPresent', 'Existing electrical box present', 'boolean', ['manualReview'], true), question('existingBoxSecure', 'Existing box appears secure', 'boolean', ['manualReview']), question('ceilingFan', 'Ceiling fan involved', 'boolean', ['labor']), question('fanRatedSupportKnown', 'Fan-rated support known', 'boolean', ['manualReview']), question('dimmerControlled', 'Dimmer-controlled', 'boolean', ['manualReview']), question('multiWayControl', 'Three-way or multi-way control', 'boolean', ['manualReview']), question('smartFixture', 'Smart fixture', 'boolean', ['labor', 'manualReview']), question('customerSuppliedMaterials', 'Customer supplying fixture', 'boolean', ['materials']), question('fixtureModel', 'Manufacturer and model', 'text', ['confidence']), question('burningOdor', 'Existing burning smell', 'boolean', ['manualReview']), question('commercialContext', 'Commercial or residential', 'singleSelect', ['scope']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, OCCUPIED_PROTECTION_MODIFIER, ...ELECTRICAL_MANUAL_REVIEW_MODIFIERS, ...ELECTRICAL_SAFETY_OVERRIDE_MODIFIERS,
    { id: 'fixture-height-9-10', name: 'Ceiling height 9–10 feet', description: 'Elevated fixture labor adjustment.', conditions: [{ field: 'ceilingHeightFeet', operator: 'greaterThan', value: 8.99 }, { field: 'ceilingHeightFeet', operator: 'lessThan', value: 10.01 }], effects: { laborMultiplier: 1.1 }, customerExplanation: 'Elevated positioning requires additional setup and work time.', internalNotes: [] },
    { id: 'fixture-height-10-16', name: 'Ceiling height over 10 through 16 feet', description: 'High-access labor and equipment adjustment.', conditions: [{ field: 'ceilingHeightFeet', operator: 'greaterThan', value: 10 }, { field: 'ceilingHeightFeet', operator: 'lessThan', value: 16.01 }], effects: { laborMultiplier: 1.35, recommendationsToAdd: ['Confirm ladder, scaffold, or lift requirements.'] }, customerExplanation: 'High-access work requires additional access planning.', internalNotes: [] },
    { id: 'fixture-height-over-16', name: 'Height over 16 feet', description: 'High-access work requires direct review.', conditions: [{ field: 'ceilingHeightFeet', operator: 'greaterThan', value: 16 }], effects: { requiresManualReview: true, manualReviewFlags: ['electricalProfessionalReviewRequired'], recommendationsToAdd: ['Schedule a high-access equipment and safety review.'] }, customerExplanation: 'Work above sixteen feet requires direct review.', internalNotes: [] },
    { id: 'fixture-heavy', name: 'Heavy fixture', description: 'Heavy fixture handling adjustment.', conditions: [{ field: 'fixtureWeightPounds', operator: 'greaterThan', value: 50 }], effects: { laborMultiplier: 1.25, requiresManualReview: true, recommendationsToAdd: ['Review second-technician and support requirements.'] }, customerExplanation: 'Heavy fixture work requires additional handling review.', internalNotes: [] },
    { id: 'fixture-ceiling-fan', name: 'Ceiling fan', description: 'Ceiling-fan labor mode.', conditions: [{ field: 'ceilingFan', operator: 'equals', value: true }], effects: { laborHoursOverride: { minimum: 2, typical: 3.5, maximum: 6 }, recommendationsToAdd: ['Confirm existing fan-rated support.'] }, customerExplanation: 'Ceiling-fan replacement uses the approved fan labor range.', internalNotes: [] },
    { id: 'fixture-assembly', name: 'Fixture assembly required', description: 'Assembly labor allowance.', conditions: [{ field: 'assemblyRequired', operator: 'equals', value: true }], effects: { flatLaborHoursRange: { minimum: 0.5, typical: 1, maximum: 2 } }, customerExplanation: 'Fixture assembly requires additional labor.', internalNotes: [] },
    { id: 'fixture-chandelier', name: 'Complex chandelier', description: 'Complex decorative fixture adjustment.', conditions: [{ field: 'complexChandelier', operator: 'equals', value: true }], effects: { laborHoursOverride: { minimum: 2, typical: 4, maximum: 8 }, laborMultiplier: 1.3, requiresManualReview: true }, customerExplanation: 'Complex chandelier work requires direct size and access review.', internalNotes: [] },
    { id: 'fixture-exterior', name: 'Exterior weather-exposed fixture', description: 'Exterior suitability adjustment.', conditions: [{ field: 'exposure', operator: 'equals', value: 'exterior' }], effects: { laborMultiplier: 1.2, recommendationsToAdd: ['Confirm fixture suitability for the exposure.'] }, customerExplanation: 'Weather exposure requires additional suitability review.', internalNotes: [] },
    { id: 'fixture-smart', name: 'Smart fixture or integrated controls', description: 'Smart-control installation adjustment.', conditions: [{ field: 'smartFixture', operator: 'equals', value: true }], effects: { flatLaborHoursRange: { minimum: 0.5, typical: 1, maximum: 2 }, recommendationsToAdd: ['Confirm fixture, dimmer, load, and control compatibility.'] }, customerExplanation: 'Smart controls require additional compatibility and setup review.', internalNotes: [] },
    { id: 'fixture-no-box', name: 'No existing electrical box', description: 'A new connection point is outside like-for-like scope.', conditions: [{ field: 'existingBoxPresent', operator: 'equals', value: false }], effects: { requiresManualReview: true, manualReviewFlags: ['electricalProfessionalReviewRequired', 'permitReviewRequired'] }, customerExplanation: 'A missing electrical box requires direct scope review.', internalNotes: [] },
    { id: 'fixture-loose-box', name: 'Loose or damaged electrical box', description: 'Box condition requires review.', conditions: [{ field: 'existingBoxSecure', operator: 'equals', value: false }], effects: { requiresManualReview: true, manualReviewFlags: ['electricalProfessionalReviewRequired'] }, customerExplanation: 'The existing box condition requires direct review.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Fixture model', 'Fixture weight', 'Ceiling height', 'Photos showing the fixture and accessible box', 'Existing control type'], reducesConfidence: ['Unknown fixture or box condition', 'Unknown height or weight', 'Complex controls'], requiredForStrongConfidence: ['fixtureCount', 'ceilingHeightFeet', 'photos'] },
  scopeOfWork: { standardSteps: ELECTRICAL_STANDARD_SCOPE, conditionalSteps: ['Remove the accessible existing fixture.', 'Assemble the included replacement fixture where required.', 'Install included mounting components and the compatible replacement fixture.'], cleanupSteps: ELECTRICAL_CLEANUP_SCOPE },
  recommendations: { relatedServices: [], customerPreparation: ['Provide the replacement fixture model, dimensions, weight, ceiling height, control type, and photos.'], professionalReviewTriggers: ['New fixture location', 'No existing or secure electrical box', 'Fan support uncertainty', 'Burned or melted wiring', 'Aluminum or knob-and-tube wiring', 'Unknown voltage', 'Water intrusion', 'Height over 16 feet', 'Fixture over 50 pounds', 'Commercial emergency or life-safety lighting', 'New circuit', 'Panel work', 'Permit or licensing uncertainty'] },
  assumptions: ['Existing circuit, approved connection point, box support, wiring, and replacement fixture are suitable and serviceable.', 'No new wiring route or structural ceiling modification is required.'],
  exclusions: ['New circuits or fixture locations', 'Significant rewiring', 'Panel work', 'Structural ceiling modification', 'Commercial emergency-light, exit-sign, or fire-alarm systems', 'High-voltage specialty lighting', 'Complex lighting controls', 'Permit fees', 'Lift rental unless included', 'Hazardous-material remediation'],
  permitsAndCode: ELECTRICAL_PERMIT_REVIEW, researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
