import type { MasterServiceTemplate } from '../../templates/masterServiceTemplate'
import { BASE_ACCESS_MODIFIERS, BASE_CONDITION_MODIFIERS, COMPANY_SCHEDULING_WINDOW, NATIONALLY_INFORMED_RESEARCH, OCCUPIED_PROTECTION_MODIFIER, STANDARD_PRICING, question } from '../profileShared'
import { ELECTRICAL_CLEANUP_SCOPE, ELECTRICAL_EQUIPMENT, ELECTRICAL_MANUAL_REVIEW_MODIFIERS, ELECTRICAL_PERMIT_REVIEW, ELECTRICAL_SAFETY_OVERRIDE_MODIFIERS, ELECTRICAL_STANDARD_SCOPE } from './electricalShared'

// Nationally informed planning assumptions. Review against completed JBTRADESMENLLC job data before final production approval.
export const switchOutletReplacement = {
  identity: { id: 'switch-outlet-replacement', slug: 'switch-outlet-replacement', version: '1.0.0', name: 'Switch or Outlet Replacement', shortName: 'Switch & Outlet', description: 'Like-for-like replacement of accessible standard switches, receptacles, GFCI receptacles, and compatible dimmers using an existing device box and circuit.', category: 'Electrical', trade: 'electrical', tags: ['switch', 'outlet', 'receptacle', 'electrical'] },
  availability: { residential: true, commercial: true, emergencyEligible: true, afterHoursEligible: true, active: true }, crew: { defaultSize: 1, minimumSize: 1, maximumRecommendedSize: 2, secondTechnicianRequired: false, secondTechnicianReason: null },
  labor: { baseHours: { minimum: 1, typical: 1.25, maximum: 2.5 }, quantityUnit: 'device', setupHours: 0.25, cleanupHours: 0.25, returnVisits: { minimum: 1, typical: 1, maximum: 2 }, minimumBillableHoursOverride: 1 },
  materials: { costRange: { minimum: 5, typical: 20, maximum: 75 }, costUnit: 'perItem', costComponents: [{ name: 'Standard replacement device', costRange: { minimum: 5, typical: 20, maximum: 75 }, costUnit: 'perItem', customerSuppliedEligible: true, applyWasteFactor: false, conditions: [{ field: 'specialtyDevice', operator: 'notEquals', value: true }] }, { name: 'Specialty, GFCI, USB, smart, or commercial device', costRange: { minimum: 20, typical: 60, maximum: 250 }, costUnit: 'perItem', customerSuppliedEligible: true, applyWasteFactor: false, conditions: [{ field: 'specialtyDevice', operator: 'equals', value: true }] }, { name: 'Connection and mounting consumables', costRange: { minimum: 5, typical: 10, maximum: 25 }, costUnit: 'perProject', customerSuppliedEligible: false, applyWasteFactor: false }], typicalMaterials: ['Replacement switch', 'Replacement receptacle', 'GFCI receptacle where selected', 'Compatible dimmer where selected', 'Wall plate', 'Approved wire connectors', 'Grounding components where applicable', 'Box-extension components when minor and approved', 'Fasteners', 'Protection materials'], wasteFactorPercentage: 0, customerSuppliedAllowed: true, materialPickupUsuallyRequired: true, specialOrderPossible: true },
  equipment: ELECTRICAL_EQUIPMENT,
  timeline: { onsiteLaborHours: { minimum: 1, typical: 2, maximum: 8 }, calendarDurationDays: { minimum: 1, typical: 1, maximum: 2 }, schedulingWindowBusinessDays: COMPANY_SCHEDULING_WINDOW, materialLeadTimeDays: { minimum: 0, typical: 3, maximum: 21 }, returnVisitRequired: false, weatherSensitive: false, permitMayAffectTimeline: true }, pricing: STANDARD_PRICING,
  estimatorQuestions: [question('deviceType', 'Switch, outlet, GFCI, dimmer, combination device, or unknown', 'singleSelect', ['labor', 'materials'], true), question('deviceCount', 'Number of devices', 'number', ['labor', 'materials'], true), question('propertyType', 'Residential or commercial', 'singleSelect', ['scope']), question('controlType', 'Standard, three-way, or four-way control', 'singleSelect', ['labor', 'manualReview']), question('smartDevice', 'Smart device', 'boolean', ['labor', 'manualReview']), question('usbReceptacle', 'USB receptacle', 'boolean', ['materials']), question('unknownVoltage', 'Device voltage unknown', 'boolean', ['manualReview']), question('existingSymptoms', 'Existing symptoms', 'text', ['confidence']), question('burnedWiring', 'Loose, cracked, warm, discolored, sparking, or burned wiring', 'boolean', ['manualReview']), question('repeatedBreakerTrips', 'Breaker trips repeatedly', 'boolean', ['manualReview']), question('groundingKnown', 'Existing grounding known', 'boolean', ['confidence']), question('neutralKnown', 'Neutral wire known', 'boolean', ['manualReview']), question('crowdedBox', 'Crowded or shallow box', 'boolean', ['labor', 'manualReview']), question('aluminumWiring', 'Aluminum wiring possibility', 'boolean', ['manualReview']), question('waterContactingElectrical', 'Water exposure contacting electrical equipment', 'boolean', ['manualReview']), question('customerSuppliedMaterials', 'Customer supplying device', 'boolean', ['materials']), question('deviceModel', 'Manufacturer and model', 'text', ['confidence']), question('photos', 'Photos', 'photo', ['confidence'], true)],
  modifiers: [...BASE_CONDITION_MODIFIERS, ...BASE_ACCESS_MODIFIERS, OCCUPIED_PROTECTION_MODIFIER, ...ELECTRICAL_MANUAL_REVIEW_MODIFIERS, ...ELECTRICAL_SAFETY_OVERRIDE_MODIFIERS,
    { id: 'device-three-way', name: 'Three-way switch', description: 'Three-way control adjustment.', conditions: [{ field: 'controlType', operator: 'equals', value: 'three-way' }], effects: { laborMultiplier: 1.2 }, customerExplanation: 'Three-way control requires additional verification and work time.', internalNotes: [] },
    { id: 'device-four-way', name: 'Four-way or multi-location control', description: 'Multi-location control adjustment.', conditions: [{ field: 'controlType', operator: 'equals', value: 'four-way' }], effects: { laborMultiplier: 1.35, requiresManualReview: true, manualReviewFlags: ['electricalProfessionalReviewRequired'] }, customerExplanation: 'Unclear multi-location control requires direct review.', internalNotes: [] },
    { id: 'device-gfci', name: 'GFCI replacement', description: 'GFCI labor mode.', conditions: [{ field: 'deviceType', operator: 'equals', value: 'gfci' }], effects: { laborHoursOverride: { minimum: 1, typical: 1.5, maximum: 3 }, laborMultiplier: 1.15 }, customerExplanation: 'GFCI replacement requires additional testing.', internalNotes: [] },
    { id: 'device-afci-gfci', name: 'AFCI/GFCI combination device', description: 'Combination-device adjustment.', conditions: [{ field: 'deviceType', operator: 'equals', value: 'afci-gfci' }], effects: { laborHoursOverride: { minimum: 1, typical: 1.5, maximum: 3 }, laborMultiplier: 1.25, recommendationsToAdd: ['Confirm circuit and device compatibility.'] }, customerExplanation: 'Combination protection devices require compatibility review.', internalNotes: [] },
    { id: 'device-smart', name: 'Smart switch', description: 'Smart device adjustment.', conditions: [{ field: 'smartDevice', operator: 'equals', value: true }], effects: { flatLaborHoursRange: { minimum: 0.5, typical: 1, maximum: 2 }, recommendationsToAdd: ['Confirm neutral, load, and control compatibility.'] }, customerExplanation: 'Smart-device setup requires additional compatibility review.', internalNotes: [] },
    { id: 'device-dimmer', name: 'Dimmer', description: 'Dimmer labor mode.', conditions: [{ field: 'deviceType', operator: 'equals', value: 'dimmer' }], effects: { laborHoursOverride: { minimum: 1, typical: 1.5, maximum: 3 }, flatLaborHoursRange: { minimum: 0.25, typical: 0.5, maximum: 1 }, recommendationsToAdd: ['Confirm fixture, lamp, and load compatibility.'] }, customerExplanation: 'Dimmer replacement requires load compatibility review.', internalNotes: [] },
    { id: 'device-crowded-box', name: 'Crowded or shallow box', description: 'Restricted box adjustment.', conditions: [{ field: 'crowdedBox', operator: 'equals', value: true }], effects: { laborMultiplier: 1.25, requiresManualReview: true, manualReviewFlags: ['electricalProfessionalReviewRequired'] }, customerExplanation: 'Visible box-fill concerns require direct review.', internalNotes: [] },
    { id: 'device-additional-units', name: 'Additional similar devices', description: 'Efficient additional-device scaling.', conditions: [{ field: 'additionalDeviceCount', operator: 'greaterThan', value: 0 }], effects: { laborHoursPerUnit: { minimum: 0.35, typical: 0.6, maximum: 1 }, laborUnitField: 'additionalDeviceCount' }, customerExplanation: 'Similar accessible devices share the initial visit setup.', internalNotes: [] }],
  confidence: { improvesConfidence: ['Device type and quantity', 'Control configuration', 'Device model', 'Box and wiring details', 'Photos'], reducesConfidence: ['Unknown voltage or wiring', 'Unclear multi-way configuration', 'Visible damage'], requiredForStrongConfidence: ['deviceType', 'deviceCount', 'photos'] },
  scopeOfWork: { standardSteps: ELECTRICAL_STANDARD_SCOPE, conditionalSteps: ['Remove the accessible existing device.', 'Install the compatible replacement device and included wall plate.', 'Test included GFCI function when applicable.'], cleanupSteps: ELECTRICAL_CLEANUP_SCOPE },
  recommendations: { relatedServices: [], customerPreparation: ['Provide device type, quantity, control configuration, model, symptoms, and photos.'], professionalReviewTriggers: ['Burned or melted wiring', 'Repeated breaker trips', 'Unknown circuit behavior or voltage', 'Aluminum or knob-and-tube wiring', 'Grounding or box-fill concern', 'Damaged box', 'Multi-wire branch circuit or shared neutral', 'Wet location', 'Commercial three-phase', 'New circuit or device location', 'Panel or breaker work', 'Life-safety or access-control equipment', 'Permit or licensing uncertainty'] },
  assumptions: ['Existing wiring is identifiable and serviceable.', 'Existing device box and selected replacement device are suitable.', 'No new wiring or circuit alteration is required.'], exclusions: ['Circuit installation or extension', 'Panel or breaker work', 'Concealed wiring repair', 'Drywall repair', 'Commercial control systems', 'Permit fees', 'Hazardous-material remediation'], permitsAndCode: ELECTRICAL_PERMIT_REVIEW, researchMetadata: NATIONALLY_INFORMED_RESEARCH,
} satisfies MasterServiceTemplate
